/* Python for Bioinformatics — 互動考題題庫 (中英雙語)
 * Bilingual question bank for the 18-chapter Python tutorial.
 * 題型 type: "single" 單選 | "multi" 多選 | "tf" 是非
 * 單選 ans: "A"|"B"|"C"|"D"
 * 多選 ans: ["A","C"]
 * 是非 ans: "T"|"F"
 * 中英對照：stem/A/B/C/D/exp 為中文；stem_en/A_en/B_en/C_en/D_en/exp_en 為英文
 */
window.QUIZ_DATA = {
  python: {
    label: "Python 生資互動考題",
    label_en: "Python BioInfo Interactive Quiz",
    labels_en: {
      "基礎篇：環境與語法": "Foundations: Environment & Syntax",
      "資料科學三大套件": "Data Science Stack",
      "序列分析": "Sequence Analysis",
      "高通量定序 (NGS)": "Next-Gen Sequencing",
      "單細胞與空間轉錄組": "Single-Cell & Spatial",
      "進階 AI 與多體學": "Advanced AI & Multi-omics",
      "Ch 1：環境設定與安裝": "Ch 1: Environment Setup",
      "Ch 2：Python 語法基礎": "Ch 2: Python Syntax",
      "Ch 3：檔案路徑與 I/O": "Ch 3: Paths & I/O",
      "Ch 4：函式、類別、模組": "Ch 4: Functions / Classes / Modules",
      "Ch 5：NumPy 數值運算": "Ch 5: NumPy",
      "Ch 6：Pandas 資料框": "Ch 6: Pandas",
      "Ch 7：視覺化 (Matplotlib/Seaborn)": "Ch 7: Visualization",
      "Ch 8：Biopython 基礎": "Ch 8: Biopython",
      "Ch 9：FASTA / FASTQ 處理": "Ch 9: FASTA / FASTQ",
      "Ch 10：BLAST 與序列比對": "Ch 10: BLAST & Alignment",
      "Ch 11：pysam 與 SAM/BAM": "Ch 11: pysam & SAM/BAM",
      "Ch 12：變異呼叫 & VCF": "Ch 12: Variant Calling & VCF",
      "Ch 13：AnnData 與 scanpy 入門": "Ch 13: AnnData & scanpy",
      "Ch 14：scRNA-seq 完整流程": "Ch 14: scRNA-seq Workflow",
      "Ch 15：空間轉錄組 (Squidpy)": "Ch 15: Spatial Transcriptomics",
      "Ch 16：多體學整合": "Ch 16: Multi-omics Integration",
      "Ch 17：單細胞 LLMs (scLLMs)": "Ch 17: Single-Cell LLMs",
      "Ch 18：AI 在生物資訊應用": "Ch 18: AI in Bioinformatics"
    },
    subjects: {
      "基礎篇：環境與語法": {
        "Ch 1：環境設定與安裝": [
          { type:"single",
            stem:"關於使用 Python 進行生物資訊分析，下列哪一種環境配置策略最佳？",
            stem_en:"Which environment-setup strategy is best for bioinformatics work in Python?",
            A:"直接用作業系統內建的 Python，全部全域安裝套件", A_en:"Use the system Python and install everything globally",
            B:"每個專案開一個獨立的 conda 環境，避免版本衝突", B_en:"Create a separate conda env per project to avoid version conflicts",
            C:"只安裝最舊的 Python 2.7 確保相容", C_en:"Stick to Python 2.7 for maximum compatibility",
            D:"全部用 pip 不要碰 conda", D_en:"Use only pip and avoid conda entirely",
            ans:"B",
            exp:"「每個專案開一個 conda env、永遠別碰 system Python」是黃金法則，能省下未來大量痛苦。",
            exp_en:"\"One conda env per project, never touch system Python\" is the golden rule — it saves enormous future pain." },
          { type:"single",
            stem:"執行 Python 腳本時跳出 ModuleNotFoundError: No module named 'scanpy'，最可能的原因是？",
            stem_en:"Running a Python script raises ModuleNotFoundError: No module named 'scanpy'. The most likely cause is?",
            A:"scanpy 已停止維護", A_en:"scanpy has been deprecated",
            B:"沒先 conda activate 對的環境，當前 Python 不是裝了 scanpy 的那個", B_en:"You forgot conda activate; current Python isn't the one with scanpy",
            C:"必須重新安裝作業系統", C_en:"You must reinstall the OS",
            D:"檔案編碼錯誤", D_en:"Wrong file encoding",
            ans:"B",
            exp:"先 conda activate 對的環境再執行；可用 which python 或 python -c 'import sys; print(sys.executable)' 確認。",
            exp_en:"Activate the right env first; verify with which python or python -c 'import sys; print(sys.executable)'." },
          { type:"single",
            stem:"關於 conda 與 pip 的混用順序，最佳實務是？",
            stem_en:"Best practice for mixing conda and pip in the same env is?",
            A:"先 pip 後 conda（pip 已裝的會被 conda 覆蓋）", A_en:"pip first, conda second (conda overwrites pip installs)",
            B:"先 conda 後 pip（pip 補 conda 找不到的套件）", B_en:"conda first, pip second (pip fills gaps conda can't cover)",
            C:"任意順序都一樣", C_en:"Order doesn't matter",
            D:"絕對不能混用", D_en:"They must never be mixed",
            ans:"B",
            exp:"先 conda 後 pip 較穩定。先 pip 後 conda 容易讓環境破損；pip 安裝完不要再 conda install。",
            exp_en:"conda first then pip is more stable. pip then conda often breaks environments; don't run conda install after pip." },
          { type:"multi",
            stem:"下列哪些是 Python 環境管理推薦的工具或做法？（多選）",
            stem_en:"Which are recommended tools/practices for Python environment management? (Multiple)",
            A:"Miniconda / Anaconda", A_en:"Miniconda / Anaconda",
            B:"匯出 env.yml 或 requirements.txt 以供重現", B_en:"Export env.yml or requirements.txt for reproducibility",
            C:"使用 mamba 加速 conda solver", C_en:"Use mamba to accelerate the conda solver",
            D:"把所有套件都安裝到 base 環境裡", D_en:"Install all packages into the base env",
            ans:["A","B","C"],
            exp:"D 不推薦：base 環境應保持乾淨；專案套件放各自 env。其他都是業界公認最佳實務。",
            exp_en:"D is not recommended — keep base clean and put per-project packages in dedicated envs. Others are standard best practice." },
          { type:"tf",
            stem:"是非題：把生資專案放在含中文或空格的路徑（如「桌面\\我的研究」）對 Python 套件不會有任何影響。",
            stem_en:"True/False: Putting bioinformatics projects under paths with spaces or non-ASCII characters has no effect on Python packages.",
            ans:"F",
            exp:"某些套件（特別是 Windows 上的 C/C++ binding）對含空格或非 ASCII 路徑會出錯。專案請放純英文、無空格路徑。",
            exp_en:"Some packages (especially Windows C/C++ bindings) fail on paths with spaces or non-ASCII characters. Use pure-ASCII paths." },
          { type:"single",
            stem:"關於 data/raw/ 資料夾的最佳實務，下列何者正確？",
            stem_en:"Best practice for the data/raw/ folder is?",
            A:"視為唯讀，原始檔不修改、不覆蓋；清洗結果寫到 processed/", A_en:"Treat as read-only — don't modify; write cleaned outputs to processed/",
            B:"直接在原檔上覆蓋修改最省空間", B_en:"Overwrite in place to save disk space",
            C:"必須提交到 git，方便協作者下載", C_en:"Must commit to git so collaborators can fetch",
            D:"資料夾名一定要含中文", D_en:"Folder name must include non-ASCII characters",
            ans:"A",
            exp:"原始資料是最珍貴的資產，永不修改；清洗結果一律輸出到 processed/。raw 資料通常太大、不宜進 git。",
            exp_en:"Raw data is your most precious asset — never modify it; write cleaned outputs to processed/. raw is usually too large to commit." },
          { type:"single",
            stem:"想把 conda 環境分享給協作者讓對方重現，最直接的命令是？",
            stem_en:"To share a conda env so collaborators can reproduce it, the most direct command is?",
            A:"conda env export --no-builds > env.yml", A_en:"conda env export --no-builds > env.yml",
            B:"複製 base 環境的所有檔案", B_en:"Copy all files from the base env",
            C:"截圖 IDE 畫面寄出", C_en:"Send IDE screenshots",
            D:"重新編譯 Python 解譯器", D_en:"Recompile the Python interpreter",
            ans:"A",
            exp:"匯出 env.yml 後，協作者用 conda env create -f env.yml 即可重建相同環境。",
            exp_en:"After exporting env.yml, collaborators run conda env create -f env.yml to recreate the identical environment." },
          { type:"tf",
            stem:"是非題：當 conda 安裝卡在「Solving environment...」很久時，可改用 mamba 大幅加速。",
            stem_en:"True/False: When conda hangs on \"Solving environment...\" for a long time, mamba can significantly speed it up.",
            ans:"T",
            exp:"mamba 是 conda 相容的 C++ 重寫版本，依賴解析速度可達 10× 以上；可用 conda install -n base mamba -c conda-forge 安裝。",
            exp_en:"mamba is a C++ reimplementation compatible with conda; dependency solving is 10× or more faster. Install via conda install -n base mamba -c conda-forge." }
        ],
        "Ch 2：Python 語法基礎": [
          { type:"single",
            stem:"執行 dna = \"ATGCGT\"; dna[1:4] 結果為何？",
            stem_en:"Result of dna = \"ATGCGT\"; dna[1:4]?",
            A:"\"ATGC\"", A_en:"\"ATGC\"",
            B:"\"TGCG\"", B_en:"\"TGCG\"",
            C:"\"TGC\"", C_en:"\"TGC\"",
            D:"\"ATG\"", D_en:"\"ATG\"",
            ans:"C",
            exp:"Python 索引 0-based、切片右端不含。dna[1:4] 取 index 1, 2, 3 → 'TGC'。",
            exp_en:"Python is 0-indexed; slice end is exclusive. dna[1:4] returns indices 1, 2, 3 → 'TGC'." },
          { type:"single",
            stem:"想快速找出兩組基因清單的「共同基因」，最適合的資料結構與運算？",
            stem_en:"To quickly find genes shared between two lists, the best data structure and operation is?",
            A:"兩個 list + 雙層 for 迴圈", A_en:"Two lists + nested for loops",
            B:"兩個 set 用 & (交集) 運算子", B_en:"Two sets with the & (intersection) operator",
            C:"兩個 dict 比 keys 一個一個對", C_en:"Two dicts comparing keys one by one",
            D:"寫一個遞迴函式", D_en:"A recursive function",
            ans:"B",
            exp:"set 自帶快速集合運算：& 交集、| 聯集、- 差集、^ 對稱差，O(n) 即完成。",
            exp_en:"Sets provide fast set operations: & intersect, | union, - diff, ^ symmetric diff, all O(n)." },
          { type:"single",
            stem:"f-string 相比舊版 % 與 .format() 最大優勢是？",
            stem_en:"Biggest advantage of f-strings over % or .format()?",
            A:"變數與格式碼可直接寫在 {} 裡，最簡潔可讀", A_en:"Variables and format specs go directly in {}, most concise and readable",
            B:"它是唯一能輸出中文的方法", B_en:"Only way to print non-ASCII",
            C:"執行速度比 print 慢 10 倍", C_en:"10× slower than print",
            D:"f-string 不需要 print()", D_en:"f-string doesn't need print()",
            ans:"A",
            exp:"f-string 直接內嵌變數與格式（如 f\"{val:.2f}\"），可讀性與速度都優於 % 與 .format()。",
            exp_en:"f-strings embed values and format specs inline (e.g., f\"{val:.2f}\") — superior readability and speed vs % or .format()." },
          { type:"multi",
            stem:"下列哪些是 Python 內建的「容器型別」？（多選）",
            stem_en:"Which are Python built-in container types? (Multiple)",
            A:"list", A_en:"list",
            B:"dict", B_en:"dict",
            C:"set", C_en:"set",
            D:"DataFrame", D_en:"DataFrame",
            ans:["A","B","C"],
            exp:"list/dict/set/tuple 都是內建容器；DataFrame 屬於 pandas，需要 import 才有。",
            exp_en:"list/dict/set/tuple are built-in; DataFrame belongs to pandas and requires importing." },
          { type:"single",
            stem:"Python 中將 DNA 序列反轉的最 Pythonic 寫法？",
            stem_en:"Most Pythonic way to reverse a DNA string?",
            A:"用 for 迴圈逐字元加到新字串", A_en:"for loop appending one char at a time",
            B:"seq[::-1]", B_en:"seq[::-1]",
            C:"使用第三方 reverse 套件", C_en:"Use a third-party reverse package",
            D:"用 numpy.flip(seq)", D_en:"numpy.flip(seq)",
            ans:"B",
            exp:"seq[::-1] 是 Python 慣用語：步長 -1 → 由後往前取一份反轉複本。",
            exp_en:"seq[::-1] is the Pythonic idiom: step -1 walks back-to-front and returns a reversed copy." },
          { type:"tf",
            stem:"是非題：Python 中字串、tuple 是不可變 (immutable)，list、dict、set 則為可變 (mutable)。",
            stem_en:"True/False: Strings and tuples are immutable in Python, while list, dict, and set are mutable.",
            ans:"T",
            exp:"這個區別重要：不可變物件可當 dict key、放進 set；可變物件不行。",
            exp_en:"Important distinction: immutable objects can be dict keys / set members; mutable ones cannot." },
          { type:"single",
            stem:"處理檔案讀寫，下列何種寫法最安全（自動關閉）？",
            stem_en:"Which file I/O pattern is safest (auto-close)?",
            A:"f = open(...); f.read(); f.close()", A_en:"f = open(...); f.read(); f.close()",
            B:"with open(...) as f: f.read()", B_en:"with open(...) as f: f.read()",
            C:"open(...).read() 一行帶過", C_en:"open(...).read() in one line",
            D:"全域變數放著不關", D_en:"Keep a global handle and never close",
            ans:"B",
            exp:"with 區塊結束時會自動呼叫 close()，即使中途例外也保證關檔。",
            exp_en:"The with block automatically calls close() on exit — even on exceptions — so the file is always closed." },
          { type:"single",
            stem:"列表推導式 [g for g in genes if g.startswith(\"M\")] 的等價 for 迴圈是？",
            stem_en:"What for-loop is equivalent to [g for g in genes if g.startswith(\"M\")]?",
            A:"out=[]; for g in genes: if g.startswith(\"M\"): out.append(g)", A_en:"out=[]; for g in genes: if g.startswith(\"M\"): out.append(g)",
            B:"out=[]; for g in genes: out.append(g)", B_en:"out=[]; for g in genes: out.append(g)",
            C:"out={}; for g in genes: out[g]=True", C_en:"out={}; for g in genes: out[g]=True",
            D:"out=set(); for g in genes: out.add(g)", D_en:"out=set(); for g in genes: out.add(g)",
            ans:"A",
            exp:"列表推導式 = 帶 filter 的迴圈：先過濾 if 條件，再把 g 加進輸出 list。",
            exp_en:"A comprehension with a filter is a for-loop with an if-guard, then appending the value." }
        ],
        "Ch 3：檔案路徑與 I/O": [
          { type:"single",
            stem:"Python 程式跳 FileNotFoundError，最該先做的診斷？",
            stem_en:"On FileNotFoundError, what should you check FIRST?",
            A:"重新安裝 Python", A_en:"Reinstall Python",
            B:"檢查 data.csv 編碼是否為 UTF-8", B_en:"Check if data.csv is UTF-8",
            C:"印出 os.getcwd() 或 Path.cwd() 看 CWD 在哪", C_en:"Print os.getcwd() / Path.cwd() to see the CWD",
            D:"把檔名改成英文", D_en:"Rename the file to ASCII",
            ans:"C",
            exp:"90% 的 FileNotFoundError 是 CWD 不在你以為的位置；先印出來確認再說。",
            exp_en:"90% of FileNotFoundError cases are wrong CWD; print it first." },
          { type:"single",
            stem:"在 Windows 上下列哪個絕對路徑寫法會出錯？",
            stem_en:"On Windows, which absolute-path style WILL break?",
            A:"\"C:/Users/charlene/data.csv\"", A_en:"\"C:/Users/charlene/data.csv\"",
            B:"\"C:\\Users\\new_data\\sample.csv\"", B_en:"\"C:\\Users\\new_data\\sample.csv\"",
            C:"r\"C:\\Users\\charlene\\data.csv\"", C_en:"r\"C:\\Users\\charlene\\data.csv\"",
            D:"Path(\"C:/Users/charlene/data.csv\")", D_en:"Path(\"C:/Users/charlene/data.csv\")",
            ans:"B",
            exp:"\\n、\\t 是字串跳脫字元，\\new 會被解析成換行+'ew'。需用正斜線、raw string，或 pathlib。",
            exp_en:"\\n / \\t are escape sequences. \\new becomes newline+'ew'. Use forward slash, raw string, or pathlib." },
          { type:"single",
            stem:"分享給協作者最 portable 的腳本路徑寫法是？",
            stem_en:"For a portable shared script, the best path pattern is?",
            A:"PROJ = Path(__file__).resolve().parent.parent，再相對地走", A_en:"PROJ = Path(__file__).resolve().parent.parent then relative",
            B:"寫死 /home/myname/proj/data/...", B_en:"Hardcode /home/myname/proj/data/...",
            C:"假設 CWD 永遠是專案根", C_en:"Assume CWD is always project root",
            D:"用桌面當工作目錄", D_en:"Use Desktop as workdir",
            ans:"A",
            exp:"以腳本自身位置為錨，再相對地走，是跨機器、跨平台都最穩的做法。",
            exp_en:"Anchor on the script's own location, then walk relatively — the most robust pattern across machines/platforms." },
          { type:"single",
            stem:"想處理大型 .gz 壓縮 FASTQ，下列哪種寫法最佳？",
            stem_en:"For a large gzipped FASTQ, which I/O pattern is best?",
            A:"f = gzip.open(\"x.fastq.gz\", \"rt\")，逐行讀取", A_en:"f = gzip.open(\"x.fastq.gz\", \"rt\"), iterate line by line",
            B:"先 gunzip 解壓再 open", B_en:"gunzip first, then open",
            C:"全部讀入記憶體再處理", C_en:"Read everything into memory first",
            D:"用 Excel 開啟", D_en:"Open in Excel",
            ans:"A",
            exp:"gzip.open(..., 'rt') 串流式逐行解壓，記憶體友善；'rt' 是 read-text 模式，得到 str。",
            exp_en:"gzip.open(..., 'rt') streams line-by-line decompression — memory friendly. 'rt' = read-text → str." },
          { type:"multi",
            stem:"下列哪些是 pathlib 比 os.path 推薦的優點？（多選）",
            stem_en:"Which are advantages of pathlib over os.path? (Multiple)",
            A:"用 / 串接路徑，跨平台自動處理斜線方向", A_en:"Chain with /, slash direction handled cross-platform",
            B:"Path 物件提供 .name/.stem/.suffix/.parent 等便利屬性", B_en:"Path objects expose .name/.stem/.suffix/.parent etc.",
            C:"是物件導向、可讀性高", C_en:"Object-oriented and readable",
            D:"完全相容 Python 2.7", D_en:"Fully compatible with Python 2.7",
            ans:["A","B","C"],
            exp:"D 錯：pathlib 是 Python 3.4+ 才有；現代專案應用 Python 3.10+。",
            exp_en:"D is wrong: pathlib is Python 3.4+. Modern projects should use Python 3.10+." },
          { type:"tf",
            stem:"是非題：寫檔案前用 Path(out_dir).mkdir(parents=True, exist_ok=True) 可避免「資料夾不存在」造成的錯誤。",
            stem_en:"True/False: Calling Path(out_dir).mkdir(parents=True, exist_ok=True) before writing avoids \"folder does not exist\" errors.",
            ans:"T",
            exp:"parents=True 會自動建上層；exist_ok=True 已存在不會報錯。是寫檔前的標準防呆。",
            exp_en:"parents=True creates intermediate dirs; exist_ok=True suppresses errors when it already exists. Standard safeguard before writing." },
          { type:"single",
            stem:"用 csv 模組讀取 TSV 檔（tab 分隔），正確指定分隔符的方式？",
            stem_en:"Reading a TSV (tab-separated) with csv module, the correct way to set the delimiter?",
            A:"csv.reader(f, delimiter=\"\\t\")", A_en:"csv.reader(f, delimiter=\"\\t\")",
            B:"csv.reader(f, sep=\"\\t\")", B_en:"csv.reader(f, sep=\"\\t\")",
            C:"csv.reader(f, separator=\"tab\")", C_en:"csv.reader(f, separator=\"tab\")",
            D:"csv.tsvreader(f)", D_en:"csv.tsvreader(f)",
            ans:"A",
            exp:"csv.reader 用 delimiter 參數；sep 是 pandas 的命名。",
            exp_en:"csv.reader uses the delimiter parameter; sep is pandas' naming." },
          { type:"single",
            stem:"open() 的模式中，哪一個會「覆蓋」既有檔案？",
            stem_en:"Which open() mode OVERWRITES an existing file?",
            A:"\"r\"", A_en:"\"r\"",
            B:"\"w\"", B_en:"\"w\"",
            C:"\"a\"", C_en:"\"a\"",
            D:"\"x\"", D_en:"\"x\"",
            ans:"B",
            exp:"\"w\" 寫入會清空既有內容；\"a\" 是附加；\"x\" 獨佔建立（已存在會失敗）。",
            exp_en:"\"w\" truncates existing content; \"a\" appends; \"x\" creates exclusively (errors if it exists)." }
        ],
        "Ch 4：函式、類別、模組": [
          { type:"single",
            stem:"def f(x, hits=[]): hits.append(x); return hits 為什麼有問題？",
            stem_en:"Why is def f(x, hits=[]): hits.append(x); return hits problematic?",
            A:"list 不能當預設值", A_en:"Lists can't be default values",
            B:"必須加 type hint", B_en:"Type hint is required",
            C:"預設值在函式定義時建立一次，會被多次呼叫共用 → 累積", C_en:"Defaults are created once at definition; calls share the same list — accumulating state",
            D:"hits 應該叫 results", D_en:"Should be named results",
            ans:"C",
            exp:"Python 函式預設值僅評估一次，可變預設會跨呼叫共享。慣用解法：用 None 當哨兵，函式內再建空 list。",
            exp_en:"Default args are evaluated once; mutable defaults persist across calls. Idiom: use None as sentinel and create an empty list inside." },
          { type:"single",
            stem:"檔尾常寫 if __name__ == \"__main__\": 的目的是？",
            stem_en:"Purpose of if __name__ == \"__main__\":",
            A:"讓檔案既可獨立執行也可被 import 而不執行 main()", A_en:"Allows the file to run standalone yet do nothing when imported",
            B:"Python 規定每個檔都要寫", B_en:"Python requires it in every file",
            C:"加速執行", C_en:"Speeds up execution",
            D:"防止記憶體洩漏", D_en:"Prevents memory leaks",
            ans:"A",
            exp:"執行時 __name__ == '__main__'；被 import 時等於模組名。讓腳本既可單獨跑也能被當函式庫使用。",
            exp_en:"When run, __name__ == '__main__'; when imported, it equals the module name. Makes the file dual-purpose." },
          { type:"single",
            stem:"@dataclass 裝飾器最大的好處是？",
            stem_en:"Main benefit of the @dataclass decorator?",
            A:"自動加密資料", A_en:"Auto-encrypts data",
            B:"自動生成 __init__、__repr__、__eq__ 等樣板碼", B_en:"Auto-generates __init__, __repr__, __eq__ boilerplate",
            C:"比一般 class 跑得快 10 倍", C_en:"10× faster than regular classes",
            D:"取代 pandas DataFrame", D_en:"Replaces pandas DataFrame",
            ans:"B",
            exp:"@dataclass 自動生成樣板方法；搭配 type hint 可有 IDE 自動補全與型別檢查。",
            exp_en:"@dataclass auto-generates boilerplate; with type hints you get IDE autocomplete and type checking." },
          { type:"multi",
            stem:"下列哪些是 Python 函式合法的「形式參數」寫法？（多選）",
            stem_en:"Which are valid Python function parameter forms? (Multiple)",
            A:"def f(x, y=2)", A_en:"def f(x, y=2)",
            B:"def f(*args)", B_en:"def f(*args)",
            C:"def f(**kwargs)", C_en:"def f(**kwargs)",
            D:"def f(x->int)", D_en:"def f(x->int)",
            ans:["A","B","C"],
            exp:"D 錯：return 型別才用 ->；參數型別應寫 def f(x: int)。",
            exp_en:"D is wrong: -> is for return types; parameter types are written def f(x: int)." },
          { type:"single",
            stem:"關於 Python 變數作用域 (LEGB)，下列敘述何者正確？",
            stem_en:"Regarding Python's LEGB scope rules, which is correct?",
            A:"在函式裡修改全域變數一定要用 global 關鍵字", A_en:"To modify a global from inside a function, you must use the global keyword",
            B:"global 變數不存在", B_en:"There's no such thing as global variables",
            C:"變數定義順序由 Built-in → Global → Enclosing → Local", C_en:"Lookup order is Built-in → Global → Enclosing → Local",
            D:"local 永遠優先於 built-in", D_en:"local always loses to built-in",
            ans:"A",
            exp:"LEGB 從 Local → Enclosing → Global → Built-in 查詢；要在函式內 reassign 全域，需 global 宣告。",
            exp_en:"LEGB looks up Local → Enclosing → Global → Built-in; to reassign a global inside a function, declare global." },
          { type:"single",
            stem:"想把多個 .py 整合成一個套件 (package)，資料夾裡通常需要包含什麼？",
            stem_en:"To turn a folder of .py files into a package, what file is typically needed?",
            A:"setup.py", A_en:"setup.py",
            B:"__init__.py（內容可為空）", B_en:"__init__.py (can be empty)",
            C:"main.py", D:"requirements.txt",
            B_en:"__init__.py (can be empty)",
            ans:"B",
            exp:"加入 __init__.py（即使空檔）可讓資料夾成為 Python package，可被 import。",
            exp_en:"Adding __init__.py (even empty) marks the folder as an importable Python package." },
          { type:"tf",
            stem:"是非題：from xxx import * 是推薦做法，因為打字最少。",
            stem_en:"True/False: from xxx import * is recommended because it requires the least typing.",
            ans:"F",
            exp:"會污染命名空間、難追蹤名稱來源；建議只 import 需要的名字或用模組別名（如 import numpy as np）。",
            exp_en:"It pollutes the namespace and obscures origins. Prefer explicit imports or aliases like import numpy as np." },
          { type:"single",
            stem:"專案結構建議：哪一層適合放「正式可重複執行的腳本」？",
            stem_en:"Recommended project layout: which folder is best for \"official repeatable scripts\"?",
            A:"notebooks/", A_en:"notebooks/",
            B:"scripts/", B_en:"scripts/",
            C:"data/raw/", C_en:"data/raw/",
            D:"results/", D_en:"results/",
            ans:"B",
            exp:"notebooks 用於探索；scripts 放正式腳本；mybio/ 放可重用模組；data/results 是資料/輸出。",
            exp_en:"notebooks for exploration; scripts for official runs; mybio/ for reusable modules; data/results for data/outputs." }
        ]
      },
      "資料科學三大套件": {
        "Ch 5：NumPy 數值運算": [
          { type:"single",
            stem:"對形狀 (100, 5) 的 NumPy 陣列執行 arr.sum(axis=0) 回傳形狀為？",
            stem_en:"For a (100, 5) ndarray, what shape does arr.sum(axis=0) return?",
            A:"(100,)", A_en:"(100,)",
            B:"(5,)", B_en:"(5,)",
            C:"(100, 5)", C_en:"(100, 5)",
            D:"純量", D_en:"a scalar",
            ans:"B",
            exp:"axis=0 沿著第 0 維加總（壓掉 row），剩下每個 column 一個值 → (5,)。",
            exp_en:"axis=0 sums along axis 0 (collapsing rows), leaving one value per column → (5,)." },
          { type:"single",
            stem:"想對表達矩陣 (cells, genes) 做 QC，保留 200<n_genes<4000 且 mt<10% 的 cell，正確語法為？",
            stem_en:"To filter cells with 200 < n_genes < 4000 AND mt% < 10, the correct syntax is?",
            A:"expr[200 < ng < 4000 and mt < 10]", A_en:"expr[200 < ng < 4000 and mt < 10]",
            B:"expr[ng > 200 and ng < 4000 and mt < 10]", B_en:"expr[ng > 200 and ng < 4000 and mt < 10]",
            C:"expr[(ng > 200) & (ng < 4000) & (mt < 10)]", C_en:"expr[(ng > 200) & (ng < 4000) & (mt < 10)]",
            D:"expr.filter(ng=[200,4000], mt=10)", D_en:"expr.filter(ng=[200,4000], mt=10)",
            ans:"C",
            exp:"NumPy 布林運算用 & | ~（且要加括號），不是 and / or（後者只能對純量）。",
            exp_en:"NumPy boolean ops use & | ~ with parentheses; not and / or (which only work on scalars)." },
          { type:"single",
            stem:"scRNA-seq 計數矩陣 10000 × 30000，最佳儲存方式為？",
            stem_en:"Best storage for a 10000 × 30000 scRNA-seq count matrix?",
            A:"scipy.sparse.csr_matrix（大部分為 0，省記憶體）", A_en:"scipy.sparse.csr_matrix (mostly zeros, huge memory savings)",
            B:"Python list of lists", B_en:"Python list of lists",
            C:"純字串", C_en:"A string",
            D:"SQL 資料庫", D_en:"A SQL database",
            ans:"A",
            exp:"scRNA-seq 計數矩陣大部分為 0；稀疏矩陣只儲存非零值，記憶體可從 GB 降到 MB。",
            exp_en:"scRNA-seq counts are mostly zero; sparse storage keeps only non-zero values, dropping memory from GB to MB." },
          { type:"single",
            stem:"NumPy 的「向量化運算」相比 Python for 迴圈，最關鍵的優勢是？",
            stem_en:"Key advantage of NumPy vectorization over Python for-loops?",
            A:"執行速度快 50-100 倍（底層 C 實作）", A_en:"50-100× faster (C-level implementation)",
            B:"程式碼比較長", B_en:"Longer code",
            C:"佔用更多記憶體", C_en:"Uses more memory",
            D:"只能在 GPU 上執行", D_en:"GPU-only",
            ans:"A",
            exp:"NumPy 用連續記憶體 + C 寫的核心，避開 Python 解譯器的 per-element 額外開銷。",
            exp_en:"NumPy uses contiguous memory + C kernels, avoiding Python interpreter per-element overhead." },
          { type:"multi",
            stem:"關於 NumPy broadcasting，下列敘述何者正確？（多選）",
            stem_en:"Which statements about NumPy broadcasting are correct? (Multiple)",
            A:"可讓不同 shape 的陣列做元素級運算", A_en:"Lets arrays of different shapes do element-wise ops",
            B:"(100, 5) 與 (5,) 相加會自動擴展", B_en:"(100, 5) + (5,) auto-expands",
            C:"(100, 5) 與 (100,) 直接相加可成功", C_en:"(100, 5) + (100,) works directly",
            D:"用 [:, None] 可把 (100,) 升維為 (100, 1)", D_en:"[:, None] reshapes (100,) into (100, 1)",
            ans:["A","B","D"],
            exp:"C 錯：(100,) 會跟最後一軸對齊，但最後一軸不是 100 而是 5。需先轉成 (100, 1)。",
            exp_en:"C is wrong: (100,) aligns to the last axis (which is 5, not 100). Reshape to (100, 1) first." },
          { type:"single",
            stem:"從 NumPy 陣列切片得到的 sub-array，預設是？",
            stem_en:"Slicing a NumPy array returns by default?",
            A:"獨立副本（不共用記憶體）", A_en:"An independent copy (no shared memory)",
            B:"view（共用記憶體，改它會動到原陣列）", B_en:"A view (shared memory; modifying it mutates the original)",
            C:"純量", C_en:"A scalar",
            D:"sparse 矩陣", D_en:"A sparse matrix",
            ans:"B",
            exp:"切片是 view；想獨立要呼叫 .copy()。布林索引與花式索引才會回傳 copy。",
            exp_en:"Slices are views; call .copy() to get a copy. Boolean and fancy indexing return copies." },
          { type:"tf",
            stem:"是非題：np.random.default_rng(seed=42) 比 np.random.seed(42) 更推薦，可重現性更佳。",
            stem_en:"True/False: np.random.default_rng(seed=42) is preferred over np.random.seed(42) for reproducibility.",
            ans:"T",
            exp:"NumPy ≥ 1.17 推薦新 Generator API；它把狀態封裝在物件中、不會被別人 import 後意外覆蓋。",
            exp_en:"NumPy ≥ 1.17 recommends the new Generator API; state is encapsulated and isn't accidentally overwritten by other modules." },
          { type:"single",
            stem:"想計算每個 cell 的總 counts（橫跨所有 genes），對 (n_cells, n_genes) 矩陣應該如何？",
            stem_en:"To compute total counts per cell on a (n_cells, n_genes) matrix:",
            A:"X.sum(axis=0)", A_en:"X.sum(axis=0)",
            B:"X.sum(axis=1)", B_en:"X.sum(axis=1)",
            C:"X.sum()", C_en:"X.sum()",
            D:"X.mean(axis=0)", D_en:"X.mean(axis=0)",
            ans:"B",
            exp:"axis=1 沿著 column 方向加總（壓掉 gene 維度），每個 cell 一個值。",
            exp_en:"axis=1 sums along columns (collapsing the gene axis), giving one value per cell." }
        ],
        "Ch 6：Pandas 資料框": [
          { type:"single",
            stem:".loc 與 .iloc 的核心區別？",
            stem_en:"Core difference between .loc and .iloc?",
            A:"速度差異", A_en:"Speed",
            B:"是否能寫入", B_en:"Whether they're writable",
            C:".loc 用標籤名、.iloc 用整數位置", C_en:".loc uses labels, .iloc uses integer positions",
            D:"沒有差別", D_en:"Interchangeable",
            ans:"C",
            exp:".loc 走標籤（含右端）、.iloc 走整數位置（不含右端）。混用是新手 bug 大宗。",
            exp_en:".loc by label (right-inclusive), .iloc by integer position (right-exclusive). Mixing them is a top source of bugs." },
          { type:"single",
            stem:"想計算每個 condition 的平均 cell 數，最簡潔的寫法是？",
            stem_en:"Cleanest way to compute mean cell count per condition?",
            A:"df.groupby(\"condition\")[\"n_cells\"].mean()", A_en:"df.groupby(\"condition\")[\"n_cells\"].mean()",
            B:"for 迴圈走訪每個 condition", B_en:"for-loop over each condition",
            C:"寫一個自訂函式", C_en:"A custom function",
            D:"df.condition.mean()", D_en:"df.condition.mean()",
            ans:"A",
            exp:"groupby + 聚合是 pandas 最常用模式；split → apply → combine 一行搞定。",
            exp_en:"groupby + aggregate is the most common pandas pattern: split → apply → combine in one line." },
          { type:"single",
            stem:"寬表 (gene × condition) 想轉成長表 (gene, condition, value)，用？",
            stem_en:"Wide (gene × condition) → long (gene, condition, value) uses?",
            A:".pivot()", A_en:".pivot()",
            B:".melt()", B_en:".melt()",
            C:".transpose()", C_en:".transpose()",
            D:".stack()", D_en:".stack()",
            ans:"B",
            exp:"melt = wide → long；pivot = long → wide。stack/unstack 也能轉但常涉及 MultiIndex。",
            exp_en:"melt = wide → long; pivot = long → wide. stack/unstack can also work but often involves MultiIndex." },
          { type:"multi",
            stem:"下列哪些是 pandas 推薦讀檔常用的選項？（多選）",
            stem_en:"Which are commonly recommended pandas read options? (Multiple)",
            A:"sep=\"\\t\" 讀 TSV", A_en:"sep=\"\\t\" for TSV",
            B:"nrows=1000 預覽前 1000 列", B_en:"nrows=1000 to preview first 1000 rows",
            C:"usecols=[\"gene\",\"fc\"] 只讀必要欄", C_en:"usecols=[\"gene\",\"fc\"] to read needed columns only",
            D:"chunksize=100000 分批迭代大檔", D_en:"chunksize=100000 to iterate large files in chunks",
            ans:["A","B","C","D"],
            exp:"四個都是處理大檔/格式變化常用技巧。",
            exp_en:"All four are standard techniques for handling large or variant-format files." },
          { type:"single",
            stem:"寫 CSV 不想保留 index 欄，正確選項？",
            stem_en:"Writing CSV without the index column:",
            A:"df.to_csv(\"out.csv\", index=False)", A_en:"df.to_csv(\"out.csv\", index=False)",
            B:"df.to_csv(\"out.csv\", drop_index=True)", B_en:"df.to_csv(\"out.csv\", drop_index=True)",
            C:"df.to_csv(\"out.csv\", no_index=True)", C_en:"df.to_csv(\"out.csv\", no_index=True)",
            D:"df.reset_index().to_csv(...)", D_en:"df.reset_index().to_csv(...)",
            ans:"A",
            exp:"to_csv 用 index=False 即可。預設 True 會多寫一欄索引，常造成下次讀回多一欄 Unnamed: 0。",
            exp_en:"to_csv accepts index=False. Default True writes an extra index column, which often appears as Unnamed: 0 on re-read." },
          { type:"single",
            stem:"處理表達矩陣的最佳檔案格式（速度與大小兼顧）為？",
            stem_en:"Best file format for expression matrices (speed + size)?",
            A:"CSV", A_en:"CSV",
            B:"Excel (xlsx)", B_en:"Excel (xlsx)",
            C:"Parquet 或 Feather（二進位、欄式）", C_en:"Parquet or Feather (binary, columnar)",
            D:"純文字 TXT", D_en:"Plain TXT",
            ans:"C",
            exp:"Parquet/Feather 二進位欄式儲存，速度比 CSV 快 10-100×、檔案小 5-10×。",
            exp_en:"Binary columnar formats are 10-100× faster and 5-10× smaller than CSV." },
          { type:"tf",
            stem:"是非題：df.query(\"mt_pct < 10 and condition == 'WT'\") 等價於 df[(df.mt_pct < 10) & (df.condition == 'WT')]。",
            stem_en:"True/False: df.query(\"mt_pct < 10 and condition == 'WT'\") is equivalent to df[(df.mt_pct < 10) & (df.condition == 'WT')].",
            ans:"T",
            exp:"query 提供更接近 SQL 的語法，可讀性高；條件多時尤其乾淨。",
            exp_en:"query offers SQL-like syntax with better readability, especially with multiple conditions." },
          { type:"single",
            stem:"連續處理（method chaining）下列哪一個寫法符合 pandas 風格？",
            stem_en:"Which method-chaining style is most pandas-idiomatic?",
            A:"df.query(\"mt < 10\").assign(rank=lambda d: d.n_cells.rank()).sort_values(\"rank\")", A_en:"df.query(\"mt < 10\").assign(rank=lambda d: d.n_cells.rank()).sort_values(\"rank\")",
            B:"先建一堆中介變數再合併", B_en:"Build many intermediate variables and merge",
            C:"用 for 迴圈逐列處理", C_en:"Iterate row by row with for loop",
            D:"轉成 numpy 再操作", D_en:"Convert to numpy and operate",
            ans:"A",
            exp:"鏈式風格簡潔可讀，且每個步驟都會回傳 DataFrame；逐列迴圈在 pandas 中是反模式。",
            exp_en:"Chaining is concise and each step returns a DataFrame; row iteration is an anti-pattern in pandas." }
        ],
        "Ch 7：視覺化 (Matplotlib/Seaborn)": [
          { type:"single",
            stem:"投稿論文圖最建議的輸出格式為？",
            stem_en:"Best output format for journal figures?",
            A:"100 dpi PNG", A_en:"100 dpi PNG",
            B:"JPG（檔小）", B_en:"JPG (small)",
            C:"PDF / SVG（向量、可放大、可在 Illustrator 編輯）", C_en:"PDF / SVG (vector, zoomable, editable in Illustrator)",
            D:"BMP", D_en:"BMP",
            ans:"C",
            exp:"PDF/SVG 是向量格式，無論放大都不失真；同時可被 Illustrator/Inkscape 編輯。",
            exp_en:"PDF/SVG are vector formats — lossless at any zoom — and editable in Illustrator/Inkscape." },
          { type:"single",
            stem:"表達量 z-score 熱圖最適合的 colormap 是？",
            stem_en:"Best colormap for a z-scored expression heatmap?",
            A:"viridis", A_en:"viridis",
            B:"RdBu_r 並設 center=0（發散型，能看出正負）", B_en:"RdBu_r with center=0 (diverging, shows sign)",
            C:"jet", C_en:"jet",
            D:"tab10", D_en:"tab10",
            ans:"B",
            exp:"z-score 有正負方向：用發散型 colormap 並 center=0，正負能立即視覺分辨。",
            exp_en:"z-scores are signed: a diverging colormap centered at 0 immediately distinguishes positive vs negative." },
          { type:"single",
            stem:"Matplotlib 推薦的 figure/axes 寫法是？",
            stem_en:"Recommended Matplotlib pattern is?",
            A:"fig, ax = plt.subplots(); ax.plot(...)", A_en:"fig, ax = plt.subplots(); ax.plot(...)",
            B:"plt.plot(...); plt.xlabel(...)", B_en:"plt.plot(...); plt.xlabel(...)",
            C:"plt.figure().plot(...)", C_en:"plt.figure().plot(...)",
            D:"兩者完全等價", D_en:"They're identical",
            ans:"A",
            exp:"OO 風格（fig/ax）可控、可重用、便於組合多子圖；隱式狀態的 plt.* 在大型程式裡容易出錯。",
            exp_en:"OO style (fig/ax) is controllable, reusable, and composable; implicit state plt.* breaks down in larger programs." },
          { type:"multi",
            stem:"下列哪些做法能讓論文圖更有「品質感」？（多選）",
            stem_en:"Which practices make figures look more publication-ready? (Multiple)",
            A:"設定 dpi=300 與 bbox_inches=\"tight\" 儲存", A_en:"Set dpi=300 and bbox_inches=\"tight\" when saving",
            B:"關閉 top/right spines、用適當留白", B_en:"Hide top/right spines and use proper whitespace",
            C:"使用 viridis/RdBu_r 等對色盲友善的 colormap", C_en:"Use colorblind-friendly maps like viridis / RdBu_r",
            D:"色彩數越多越好，盡量用 jet", D_en:"More colors, e.g. jet, the better",
            ans:["A","B","C"],
            exp:"D 錯：jet 對色盲不友善、感知不均勻，Nature Methods 也建議改用 viridis 系列。",
            exp_en:"D is wrong: jet is colorblind-hostile and perceptually non-uniform; Nature Methods recommends viridis instead." },
          { type:"single",
            stem:"想畫小提琴圖加上散點 (jitter) 顯示每個樣本，最簡潔的 Seaborn 寫法是？",
            stem_en:"Cleanest Seaborn way to draw a violin plot overlaid with sample-level dots:",
            A:"sns.violinplot + sns.stripplot 疊加", A_en:"sns.violinplot + sns.stripplot overlay",
            B:"用 matplotlib 純手動繪製", B_en:"Hand-draw with raw matplotlib",
            C:"sns.heatmap", C_en:"sns.heatmap",
            D:"sns.lineplot", D_en:"sns.lineplot",
            ans:"A",
            exp:"violinplot + stripplot 疊加是看分布 + 樣本數的標準組合，無需額外設定。",
            exp_en:"violinplot + stripplot overlay is the standard combo to show distribution and individual points." },
          { type:"single",
            stem:"想標出 volcano plot 上 padj<0.05 與 |log2FC|>1 的基因，最直觀的做法是？",
            stem_en:"To highlight genes with padj<0.05 and |log2FC|>1 on a volcano plot:",
            A:"用三類顏色分別畫 UP/DOWN/NS 三組散點", A_en:"Draw three scatter groups (UP/DOWN/NS) in different colors",
            B:"全部用同一種顏色", B_en:"Use one color for all",
            C:"只用點大小區分", C_en:"Use point size only",
            D:"全部標文字標籤", D_en:"Label every gene",
            ans:"A",
            exp:"先用 np.where 或條件分組成三類，再分別畫散點上不同顏色；只標 top hits 的文字，避免文字爆炸。",
            exp_en:"Use np.where or conditional grouping into three classes; label only top hits to avoid text overload." },
          { type:"tf",
            stem:"是非題：cluster 數小於 10 時用 tab10 categorical palette；超過 20 時直接套 jet。",
            stem_en:"True/False: Use tab10 for <10 clusters; for >20 clusters, use jet.",
            ans:"F",
            exp:"超過 20 類時應考慮合併或用 scanpy 的 default_102 等更廣的 palette；jet 不該用於任何情況。",
            exp_en:"For >20 categories, consider merging or use scanpy's default_102; jet should not be used in any case." },
          { type:"single",
            stem:"想讓全圖的字型統一為 Arial 11 pt，最有效率的做法是？",
            stem_en:"Most efficient way to set the entire figure to Arial 11pt:",
            A:"在腳本最上方一次設定 plt.rcParams 全域字型", A_en:"Set plt.rcParams globally at the top of the script",
            B:"每個 ax.text() 都帶 fontfamily 參數", B_en:"Pass fontfamily to every ax.text() call",
            C:"每個 ax.set_xlabel/ylabel 各設一次", C_en:"Set each ax.set_xlabel/ylabel individually",
            D:"必須改 system 字型", D_en:"Must edit system fonts",
            ans:"A",
            exp:"plt.rcParams 設一次後全圖通用；維護方便、輸出風格一致。",
            exp_en:"plt.rcParams sets it once and applies everywhere — easier maintenance and consistent output." }
        ]
      },
      "序列分析": {
        "Ch 8：Biopython 基礎": [
          { type:"single",
            stem:"Seq(\"ATGTAA\").translate() 結果是？",
            stem_en:"Seq(\"ATGTAA\").translate() returns?",
            A:"Seq('M')", A_en:"Seq('M')",
            B:"Seq('M*')", B_en:"Seq('M*')",
            C:"Seq('ATGTAA')", C_en:"Seq('ATGTAA')",
            D:"報錯", D_en:"Error",
            ans:"B",
            exp:"ATG → M (Met)；TAA → * (stop)。要在第一個 stop 停止可加 to_stop=True。",
            exp_en:"ATG → M; TAA → * (stop). Use to_stop=True to halt at the first stop." },
          { type:"single",
            stem:"使用 Bio.Entrez 抓 NCBI 資料前必須做的事？",
            stem_en:"Mandatory step before using Bio.Entrez:",
            A:"註冊 NCBI 帳號", A_en:"Register an NCBI account",
            B:"申請 API key", B_en:"Apply for API key",
            C:"設定 Entrez.email = \"...\"", C_en:"Set Entrez.email = \"...\"",
            D:"安裝 R", D_en:"Install R",
            ans:"C",
            exp:"NCBI 規定要提供 email，用量過大時可聯絡而不是直接封 IP。API key 是選用，提升配額。",
            exp_en:"NCBI requires an email so they can contact you instead of blocking. API key is optional and raises rate limits." },
          { type:"single",
            stem:"SeqRecord 比純 Seq 多了什麼好處？",
            stem_en:"What does SeqRecord add over a bare Seq?",
            A:"id / description / features 等 metadata", A_en:"id / description / features metadata",
            B:"執行速度快", B_en:"Faster execution",
            C:"可儲存影像", C_en:"Can store images",
            D:"Seq 已停止維護", D_en:"Seq is deprecated",
            ans:"A",
            exp:"SeqRecord 是 Seq 加 metadata 的容器，更貼近 GenBank/UniProt 的實際資料模型。",
            exp_en:"SeqRecord wraps Seq with metadata — closer to GenBank/UniProt's actual data model." },
          { type:"multi",
            stem:"下列哪些操作 Biopython 都能做？（多選）",
            stem_en:"Which operations can Biopython handle? (Multiple)",
            A:"DNA 反向互補", A_en:"DNA reverse complement",
            B:"DNA → 蛋白質翻譯（含密碼子表）", B_en:"DNA → protein translation (codon tables)",
            C:"從 NCBI 下載序列", C_en:"Download sequences from NCBI",
            D:"執行 GPU 訓練深度學習模型", D_en:"Run GPU deep learning training",
            ans:["A","B","C"],
            exp:"D 屬於 PyTorch/TensorFlow 領域；前三項都是 Biopython 的核心功能。",
            exp_en:"D belongs to PyTorch/TensorFlow; the others are Biopython core features." },
          { type:"single",
            stem:"想在序列上找開放讀框 (ORF)，下列哪一個是必要步驟？",
            stem_en:"To find ORFs on a sequence, a necessary step is:",
            A:"在三個讀框（六個含反向）中找 M 起點到 * 終止的片段", A_en:"In all three frames (six including reverse), find segments from M to *",
            B:"只看正股一個讀框", B_en:"Only look at one frame on the forward strand",
            C:"先做 PCA", C_en:"Run PCA first",
            D:"必須先 BLAST", D_en:"Must BLAST first",
            ans:"A",
            exp:"ORF 可能在 6 個讀框任一中；標準做法是六框翻譯後找 M…* 片段，套用最小長度閾值。",
            exp_en:"ORFs can appear in any of 6 frames; translate all six and find M…* segments with a minimum length cutoff." },
          { type:"single",
            stem:"想用粒線體密碼子表翻譯，最簡潔的 Biopython 寫法？",
            stem_en:"Translating with a mitochondrial codon table — the cleanest Biopython call:",
            A:"dna.translate(table=\"Vertebrate Mitochondrial\")", A_en:"dna.translate(table=\"Vertebrate Mitochondrial\")",
            B:"自己手動寫密碼子表", B_en:"Write the codon table yourself",
            C:"用 numpy.translate", C_en:"Use numpy.translate",
            D:"必須安裝 R", D_en:"Must install R",
            ans:"A",
            exp:"Biopython 內建 NCBI 全部 codon 表，translate(table=...) 直接切換。",
            exp_en:"Biopython ships all NCBI codon tables — translate(table=...) switches instantly." },
          { type:"tf",
            stem:"是非題：Biopython 的 SeqRecord 切片會自動帶著 features 與 quality 資訊一起切。",
            stem_en:"True/False: Slicing a SeqRecord automatically carries along features and qualities.",
            ans:"T",
            exp:"SeqRecord 切片會更新位置並保留對應的 features 與 letter_annotations，這對 FASTQ trimming 特別有用。",
            exp_en:"SeqRecord slicing updates positions and preserves features/letter_annotations — handy for FASTQ trimming." },
          { type:"single",
            stem:"從 Biopython 取得 DNA 反向互補最直接的呼叫是？",
            stem_en:"Most direct way to get a DNA reverse complement in Biopython:",
            A:"dna.reverse_complement()", A_en:"dna.reverse_complement()",
            B:"reversed(dna)", B_en:"reversed(dna)",
            C:"dna.flip()", C_en:"dna.flip()",
            D:"必須自己寫 dict", D_en:"Must hand-roll a dict",
            ans:"A",
            exp:"Seq 物件直接提供 .reverse_complement()；亦可單獨 .complement()。",
            exp_en:"The Seq object exposes .reverse_complement() (and .complement() separately)." }
        ],
        "Ch 9：FASTA / FASTQ 處理": [
          { type:"single",
            stem:"FASTQ 品質字元 'I' 對應的 Phred 分數 (Sanger) 是？",
            stem_en:"Phred score (Sanger) for FASTQ char 'I' is?",
            A:"0", A_en:"0",
            B:"20", B_en:"20",
            C:"40 (因為 ord('I')=73, 73-33=40)", C_en:"40 (ord('I')=73, 73-33=40)",
            D:"73", D_en:"73",
            ans:"C",
            exp:"Sanger / Illumina 1.8+ 用 ASCII offset 33；Q = ord(char) - 33。Q40 對應 99.99% 準確率。",
            exp_en:"Sanger / Illumina 1.8+ uses ASCII offset 33; Q = ord(char) - 33. Q40 = 99.99% accuracy." },
          { type:"single",
            stem:"處理 20 GB FASTQ.gz 想最快地數 reads 數，最佳工具？",
            stem_en:"Counting reads in a 20 GB FASTQ.gz — fastest option?",
            A:"SeqIO.parse() 走訪", A_en:"Iterate via SeqIO.parse()",
            B:"pyfastx.Fastq(...) + len()（有 index 後 O(1)）", B_en:"pyfastx.Fastq(...) + len() (O(1) once indexed)",
            C:"完全解壓再 wc -l", C_en:"Decompress fully then wc -l",
            D:"用 pandas 讀", D_en:"Use pandas",
            ans:"B",
            exp:"pyfastx 是 C++ 寫的，建立 index 後查 read 數 O(1)；比 SeqIO.parse() 快數十倍。",
            exp_en:"pyfastx is C++; with an index, read counting is O(1) — dozens of times faster than SeqIO.parse()." },
          { type:"single",
            stem:"SeqIO.parse() 與 SeqIO.read() 的差別？",
            stem_en:"Difference between SeqIO.parse() and SeqIO.read()?",
            A:"parse 回傳 generator (多筆)，read 回傳單一 record (檔案只有 1 條)", A_en:"parse returns a generator (many records); read returns one record (file must contain one)",
            B:"read 比 parse 快", B_en:"read is faster than parse",
            C:"parse 只能讀 FASTA、read 只能讀 FASTQ", C_en:"parse only reads FASTA; read only reads FASTQ",
            D:"完全相同", D_en:"They're identical",
            ans:"A",
            exp:"用 read 處理多筆檔會報錯。parse 是 generator，逐筆 yield 適合大檔。",
            exp_en:"read errors if multiple records are present. parse is a generator yielding one record at a time — suitable for large files." },
          { type:"single",
            stem:"FASTQ 檔的「第 4 行」存的是什麼？",
            stem_en:"What does the 4th line of a FASTQ record contain?",
            A:"序列 ID", A_en:"Sequence ID",
            B:"DNA 序列", B_en:"DNA sequence",
            C:"+ 分隔符", C_en:"The + separator",
            D:"品質分數字串（每字元對應序列上的一個 base）", D_en:"Quality string (one char per base in the sequence)",
            ans:"D",
            exp:"FASTQ 一筆 = 4 行：@ID / 序列 / + / 品質字串。前後行字數需一致。",
            exp_en:"A FASTQ record = 4 lines: @ID / sequence / + / quality. Lines 2 and 4 must have equal length." },
          { type:"multi",
            stem:"下列哪些是定序資料 QC 中常見的關注點？（多選）",
            stem_en:"Which are common concerns in sequencing QC? (Multiple)",
            A:"每位置品質曲線", A_en:"Per-base quality curve",
            B:"adapter 污染", B_en:"Adapter contamination",
            C:"GC 分佈", C_en:"GC distribution",
            D:"重複序列比例", D_en:"Duplication ratio",
            ans:["A","B","C","D"],
            exp:"四項都是 FastQC 等工具的標準輸出。",
            exp_en:"All four are standard FastQC outputs." },
          { type:"single",
            stem:"想用 SeqIO 過濾低品質 reads，最簡潔的策略？",
            stem_en:"Cleanest SeqIO strategy to filter low-quality reads?",
            A:"在 generator 內檢查 letter_annotations[\"phred_quality\"] 平均後 yield 高品質的 record", A_en:"In a generator, inspect letter_annotations[\"phred_quality\"] mean and yield high-Q records",
            B:"全部讀進記憶體再過濾", B_en:"Read all into memory then filter",
            C:"用 grep \"高品質\"", C_en:"grep \"high quality\"",
            D:"必須先轉成 BAM", D_en:"Convert to BAM first",
            ans:"A",
            exp:"用 generator 串流，記憶體小、可串接 SeqIO.write 直接寫出乾淨檔。",
            exp_en:"Streaming via generator is memory-efficient and chains directly into SeqIO.write." },
          { type:"tf",
            stem:"是非題：要讀 .gz 壓縮檔，gzip.open() 應傳 mode=\"rt\" 才能得到 str（不是 bytes）。",
            stem_en:"True/False: To read gzipped text, gzip.open() should use mode=\"rt\" to return str (not bytes).",
            ans:"T",
            exp:"\"rt\" = read text；不指定 t 是二進位模式 (rb)。記得加 encoding=\"ascii\" 或 \"utf-8\"。",
            exp_en:"\"rt\" = read text; without t it defaults to binary (rb). Pair with encoding=\"ascii\" or \"utf-8\"." },
          { type:"single",
            stem:"FASTA 與 FASTQ 主要差異是？",
            stem_en:"Primary difference between FASTA and FASTQ:",
            A:"FASTQ 多了品質分數行，常用於原始 reads；FASTA 沒有品質，常用於成品序列", A_en:"FASTQ has quality lines and stores raw reads; FASTA has no quality and stores assembled sequences",
            B:"FASTA 只給蛋白用、FASTQ 只給 DNA 用", B_en:"FASTA is for proteins only; FASTQ is for DNA only",
            C:"兩者完全相同", C_en:"They're identical",
            D:"FASTQ 一定要 .gz", D_en:"FASTQ must always be .gz",
            ans:"A",
            exp:"FASTA 通常存基因組/轉錄本/蛋白；FASTQ 存定序原始 reads，多了品質字串便於 QC。",
            exp_en:"FASTA stores genomes/transcripts/proteins; FASTQ stores raw reads with quality strings for QC." }
        ],
        "Ch 10：BLAST 與序列比對": [
          { type:"single",
            stem:"BLAST E-value 越「小」代表？",
            stem_en:"A smaller BLAST E-value means:",
            A:"比對結果越短", A_en:"Alignment is shorter",
            B:"比對結果越長", B_en:"Alignment is longer",
            C:"越不可能是隨機巧合，比對越可信", C_en:"Less likely to be random — more credible hit",
            D:"越可能是錯誤", D_en:"More likely an error",
            ans:"C",
            exp:"E-value 是「靠運氣得到此分數的期望次數」，越小越可信。E < 1e-5 通常算顯著。",
            exp_en:"E-value = expected number of chance hits at this score; smaller is more credible. E < 1e-5 is usually significant." },
          { type:"single",
            stem:"一條未知 DNA 序列想知道它編碼的可能蛋白功能，最適合？",
            stem_en:"Unknown DNA; want the encoded protein's likely function. Best tool?",
            A:"blastn", A_en:"blastn",
            B:"blastx (DNA → 6 frames → 蛋白 DB)", B_en:"blastx (DNA → 6 frames → protein DB)",
            C:"BWA", C_en:"BWA",
            D:"MAFFT", D_en:"MAFFT",
            ans:"B",
            exp:"blastx 把 query 翻譯六框後對蛋白資料庫，能找到跨物種的 distant homologs，適合功能推論。",
            exp_en:"blastx translates the query in six frames vs. protein DB; finds distant homologs across species — ideal for functional inference." },
          { type:"single",
            stem:"跨資料庫比較相似度時，較公平的指標為？",
            stem_en:"Fairer metric when comparing similarity across databases:",
            A:"bit score（不受 DB 大小影響）", A_en:"bit score (DB-size independent)",
            B:"E-value", B_en:"E-value",
            C:"% identity", C_en:"% identity",
            D:"alignment length", D_en:"Alignment length",
            ans:"A",
            exp:"bit score 與 DB 大小無關；E-value 會隨 DB 大小膨脹/縮小，不適合跨 DB 比較。",
            exp_en:"bit score is DB-independent; E-value scales with DB size and is unsuitable for cross-DB comparison." },
          { type:"single",
            stem:"上百萬條短 reads 想對到參考基因組，最適合的工具？",
            stem_en:"Best tool for aligning millions of short reads to a reference?",
            A:"BLAST", A_en:"BLAST",
            B:"BWA-MEM2 / Bowtie2", B_en:"BWA-MEM2 / Bowtie2",
            C:"MAFFT", C_en:"MAFFT",
            D:"pairwise2", D_en:"pairwise2",
            ans:"B",
            exp:"BLAST 太慢；NGS short read alignment 業界標準是 BWA-MEM2 / Bowtie2 / STAR (RNA-seq)。",
            exp_en:"BLAST is too slow; the NGS short-read alignment standard is BWA-MEM2 / Bowtie2 / STAR (RNA-seq)." },
          { type:"multi",
            stem:"關於序列比對工具，下列敘述何者正確？（多選）",
            stem_en:"Which are correct about alignment tools? (Multiple)",
            A:"Minimap2 適合 PacBio / Nanopore 長 reads", A_en:"Minimap2 fits PacBio / Nanopore long reads",
            B:"MUSCLE / MAFFT 是多序列比對 (MSA) 工具", B_en:"MUSCLE / MAFFT are multiple-sequence alignment (MSA) tools",
            C:"Bio.Align.PairwiseAligner 用於兩條序列的小規模比對", C_en:"Bio.Align.PairwiseAligner is for small-scale pairwise alignment",
            D:"BLAST 是全域比對 (global alignment) 工具", D_en:"BLAST is a global alignment tool",
            ans:["A","B","C"],
            exp:"D 錯：BLAST 是區域比對 (local alignment) — 找的是序列裡相似的「片段」。",
            exp_en:"D is wrong: BLAST is local alignment — it finds similar fragments, not full-length alignment." },
          { type:"single",
            stem:"蛋白質距離較遠（identity ~30%）但功能相似，下列敘述何者正確？",
            stem_en:"Distantly related proteins (~30% identity) with shared function:",
            A:"% identity 很低就一定不是同源", A_en:"Low % identity means definitely not homologous",
            B:"可結合 bit score > 50 與保守 motif 來判斷 distant homology", B_en:"Combine bit score > 50 and conserved motifs to call distant homology",
            C:"BLAST 完全無能為力", C_en:"BLAST is useless",
            D:"應該換用 BWA", D_en:"Should switch to BWA",
            ans:"B",
            exp:"% identity 低不代表沒同源；蛋白可能 30% identity 但結構/功能完全保留。實務上看 bit score 加 motif 證據。",
            exp_en:"Low identity doesn't preclude homology; proteins at 30% can keep full structure/function. Combine bit score with motif evidence." },
          { type:"tf",
            stem:"是非題：本機 BLAST 之前必須用 makeblastdb 建立資料庫索引。",
            stem_en:"True/False: Local BLAST requires makeblastdb to build a database index first.",
            ans:"T",
            exp:"makeblastdb -in xxx.fa -dbtype prot/nucl -out my_db 後才能用 blastp/blastn 搜尋。",
            exp_en:"After makeblastdb -in xxx.fa -dbtype prot/nucl -out my_db, blastp/blastn can search against it." },
          { type:"single",
            stem:"演化分析想建樹，標準流程是？",
            stem_en:"Standard pipeline for phylogenetic tree construction:",
            A:"先 BWA 對位再建樹", A_en:"BWA align first, then tree",
            B:"先 MSA (MAFFT/MUSCLE) → 再建樹 (IQ-TREE/RAxML)", B_en:"MSA first (MAFFT/MUSCLE) → tree (IQ-TREE/RAxML)",
            C:"用 PCA 取代", C_en:"Use PCA instead",
            D:"直接看序列即可", D_en:"Just eyeball sequences",
            ans:"B",
            exp:"建樹流程：MSA 對齊 → 距離/最大似然法建樹（IQ-TREE/RAxML/MrBayes）→ 自助法檢定 (bootstrap)。",
            exp_en:"Phylogenetics workflow: MSA → distance/ML tree (IQ-TREE/RAxML/MrBayes) → bootstrap." }
        ]
      },
      "高通量定序 (NGS)": {
        "Ch 11：pysam 與 SAM/BAM": [
          { type:"single",
            stem:"想用 pysam 抓 chr1:1000-2000 區段的 reads，BAM 檔需要？",
            stem_en:"To fetch reads from chr1:1000-2000 with pysam, the BAM file needs:",
            A:"沒有特殊需求", A_en:"Nothing special",
            B:"必須先轉成 SAM", B_en:"Must be converted to SAM first",
            C:"必須是 sorted BAM 並有 .bai 索引", C_en:"Must be sorted BAM with a .bai index",
            D:"必須是 CRAM", D_en:"Must be CRAM",
            ans:"C",
            exp:"區段查詢需 sorted + indexed；用 samtools sort 排序後 samtools index 建 .bai。",
            exp_en:"Region queries require sorted + indexed; samtools sort then samtools index creates .bai." },
          { type:"single",
            stem:"CIGAR 字串 30M2I50M 代表什麼？",
            stem_en:"CIGAR 30M2I50M means:",
            A:"30 match + 2 deletion + 50 match", A_en:"30 match + 2 deletion + 50 match",
            B:"30 match + 2-base insertion (read 多出來) + 50 match", B_en:"30 match + 2-base insertion (read has extra) + 50 match",
            C:"32 mismatch + 50 match", C_en:"32 mismatch + 50 match",
            D:"read 長度 = 80 bp", D_en:"read length = 80 bp",
            ans:"B",
            exp:"I = insertion in read（read 比 ref 多出 2 個 base）；read 長度 = 30+2+50 = 82。",
            exp_en:"I = insertion in read (2 bases more than reference); read length = 30+2+50 = 82." },
          { type:"single",
            stem:"read.reference_start 在 pysam 是 0-based。SAM POS 是 1-based。直接貼到 IGV：",
            stem_en:"read.reference_start in pysam is 0-based; SAM POS is 1-based. Pasting pysam's value to IGV:",
            A:"位置會差 1 個 base — 須先 +1", A_en:"Off by one — add +1 first",
            B:"完全沒事", B_en:"No issue",
            C:"IGV 會自動修正", C_en:"IGV auto-corrects",
            D:"整個位置會錯一條染色體", D_en:"Whole chromosome shifts",
            ans:"A",
            exp:"BED/BAM/pysam 是 0-based half-open；SAM/VCF/GFF 是 1-based fully-closed。記得換算！",
            exp_en:"BED/BAM/pysam are 0-based half-open; SAM/VCF/GFF are 1-based closed. Always convert!" },
          { type:"multi",
            stem:"關於 SAM FLAG 欄位，下列敘述正確的有哪些？（多選）",
            stem_en:"Which statements about the SAM FLAG field are correct? (Multiple)",
            A:"是位元欄位 (bitfield)，可以同時編碼多個屬性", A_en:"It's a bitfield encoding multiple properties simultaneously",
            B:"FLAG=4 代表 unmapped", B_en:"FLAG=4 means unmapped",
            C:"FLAG=1024 代表 PCR 重複", C_en:"FLAG=1024 means PCR duplicate",
            D:"FLAG 只有 0 或 1 兩個值", D_en:"FLAG only has 0 or 1",
            ans:["A","B","C"],
            exp:"D 錯：FLAG 是 12 個 bit 的位元組合，可達 4095；常用 picard 線上工具解碼。",
            exp_en:"D is wrong: FLAG is a 12-bit field up to 4095; Picard's online tool decodes them." },
          { type:"single",
            stem:"想計算一段區的 coverage profile（每個 base 多少 reads 覆蓋），最直接的 pysam 呼叫？",
            stem_en:"Most direct pysam call to compute a per-base coverage profile in a region:",
            A:"bam.pileup(chrom, start, end, truncate=True) 並讀 col.nsegments", A_en:"bam.pileup(chrom, start, end, truncate=True) and read col.nsegments",
            B:"bam.read()", B_en:"bam.read()",
            C:"bam.write()", C_en:"bam.write()",
            D:"bam.search()", D_en:"bam.search()",
            ans:"A",
            exp:"pileup 提供 per-base 訪問，nsegments 是該位置覆蓋的 reads 數。",
            exp_en:"pileup provides per-base access; nsegments is the number of reads covering that position." },
          { type:"single",
            stem:"BAM 與 CRAM 最大差異是？",
            stem_en:"Biggest difference between BAM and CRAM:",
            A:"CRAM 較小、需要參考基因組才能解碼", A_en:"CRAM is smaller and requires the reference for decoding",
            B:"CRAM 無法被 pysam 處理", B_en:"CRAM can't be handled by pysam",
            C:"BAM 是純文字、CRAM 是二進位", C_en:"BAM is plain text and CRAM is binary",
            D:"兩者完全相同", D_en:"They're identical",
            ans:"A",
            exp:"CRAM 用參考基因組做差異壓縮，比 BAM 再小 30-50%；解碼時需要對應的 reference。",
            exp_en:"CRAM uses reference-based delta compression — 30-50% smaller than BAM but needs the reference to decode." },
          { type:"tf",
            stem:"是非題：寫 BAM 輸出時要把 inbam 當作 template 傳給 AlignmentFile，輸出檔才會帶正確的 header。",
            stem_en:"True/False: When writing a BAM, pass the input BAM as template to AlignmentFile so the output inherits the correct header.",
            ans:"T",
            exp:"out = pysam.AlignmentFile('clean.bam', 'wb', template=inbam) 是標準寫法。",
            exp_en:"out = pysam.AlignmentFile('clean.bam', 'wb', template=inbam) is the standard pattern." },
          { type:"single",
            stem:"標記 PCR duplicate 的最常用工具是？",
            stem_en:"Most common tool to mark PCR duplicates:",
            A:"BLAST", A_en:"BLAST",
            B:"Picard MarkDuplicates / samtools markdup", B_en:"Picard MarkDuplicates / samtools markdup",
            C:"FastQC", C_en:"FastQC",
            D:"BWA", D_en:"BWA",
            ans:"B",
            exp:"PCR/光學重複用 Picard MarkDuplicates 或 samtools markdup 標記後，下游 variant calling 才會排除。",
            exp_en:"PCR/optical duplicates are marked with Picard MarkDuplicates or samtools markdup so variant callers can exclude them." }
        ],
        "Ch 12：變異呼叫 & VCF": [
          { type:"single",
            stem:"VCF 的 GT=0/1 代表？",
            stem_en:"VCF GT=0/1 means:",
            A:"純合野生", A_en:"Homozygous reference",
            B:"純合突變", B_en:"Homozygous alternate",
            C:"異合（一條 ref、一條 alt）", C_en:"Heterozygous (one ref, one alt)",
            D:"缺失值", D_en:"Missing",
            ans:"C",
            exp:"GT=0/0 純合野生、0/1 異合、1/1 純合突變、./. 缺失。",
            exp_en:"GT=0/0 hom ref, 0/1 het, 1/1 hom alt, ./. missing." },
          { type:"single",
            stem:"處理千樣本級 cohort VCF 想最快跑完，最佳選擇？",
            stem_en:"Fastest parser for cohort-scale VCF (thousands of samples)?",
            A:"PyVCF", A_en:"PyVCF",
            B:"cyvcf2（C 編譯，速度極快）", B_en:"cyvcf2 (C-compiled, very fast)",
            C:"純 csv 模組逐行讀", C_en:"csv module line-by-line",
            D:"Excel", D_en:"Excel",
            ans:"B",
            exp:"cyvcf2 用 C 寫，比 PyVCF 快 50× 以上；htslib 為基底，與 bcftools 同核心。",
            exp_en:"cyvcf2 is C-compiled — >50× faster than PyVCF; built on htslib (same core as bcftools)." },
          { type:"single",
            stem:"GATK Best Practices 在 BAM 處理階段必做的關鍵步驟？",
            stem_en:"Key BAM-processing step in GATK Best Practices:",
            A:"標記重複 (MarkDuplicates) + BQSR", A_en:"MarkDuplicates + BQSR",
            B:"把 BAM 轉回 FASTQ", B_en:"Convert BAM back to FASTQ",
            C:"再 BLAST 一次", C_en:"Re-run BLAST",
            D:"跳過排序直接 call", D_en:"Skip sorting", ans:"A",
            exp:"標準流程：sort → MarkDuplicates → BQSR → HaplotypeCaller → joint genotyping。",
            exp_en:"Standard pipeline: sort → MarkDuplicates → BQSR → HaplotypeCaller → joint genotyping." },
          { type:"multi",
            stem:"下列哪些屬於變異類型？（多選）",
            stem_en:"Which are variant types? (Multiple)",
            A:"SNP / SNV（單一 base 取代）", A_en:"SNP / SNV (single base substitution)",
            B:"Indel（小段插入/刪除）", B_en:"Indel (small insertion/deletion)",
            C:"SV（>50 bp 結構變異）", C_en:"SV (>50 bp structural variant)",
            D:"CNV（複本數變異）", D_en:"CNV (copy number variant)",
            ans:["A","B","C","D"],
            exp:"四項都是常見變異類型，使用不同的呼叫工具（GATK/Manta/CNVkit 等）。",
            exp_en:"All four are common variant types, called by different tools (GATK/Manta/CNVkit etc.)." },
          { type:"single",
            stem:"癌細胞 vs 正常組織的 somatic 變異呼叫，常用工具是？",
            stem_en:"Common somatic variant callers (tumor vs normal):",
            A:"Mutect2 / Strelka / VarScan", A_en:"Mutect2 / Strelka / VarScan",
            B:"BLAST", B_en:"BLAST",
            C:"FastQC", C_en:"FastQC",
            D:"DESeq2", D_en:"DESeq2",
            ans:"A",
            exp:"Somatic 突變呼叫器假設「正常 + 腫瘤」配對；Mutect2/Strelka/VarScan 是業界標準。",
            exp_en:"Somatic callers assume tumor-normal pairs; Mutect2/Strelka/VarScan are industry standards." },
          { type:"single",
            stem:"VCF 的 INFO 欄位 ##INFO=<ID=DP,...> 通常代表？",
            stem_en:"VCF INFO field ##INFO=<ID=DP,...> typically means:",
            A:"該位點的總覆蓋深度 (depth)", A_en:"Total depth at this site",
            B:"基因型品質", B_en:"Genotype quality",
            C:"等位基因頻率", C_en:"Allele frequency",
            D:"突變型別", D_en:"Variant type",
            ans:"A",
            exp:"DP = total Depth；VCF 標頭定義各欄位意義，常見還有 AF (allele freq)、QD、FS、SOR。",
            exp_en:"DP = total depth; the VCF header defines field meanings (also AF, QD, FS, SOR)." },
          { type:"tf",
            stem:"是非題：完整的變異呼叫 pipeline 通常用 Snakemake 或 Nextflow 串接。",
            stem_en:"True/False: Full variant calling pipelines are typically orchestrated with Snakemake or Nextflow.",
            ans:"T",
            exp:"nf-core/sarek（cancer/germline）、snakemake-workflows/dna-seq-* 都是經典開源實作。",
            exp_en:"Classic open-source examples: nf-core/sarek (cancer/germline), snakemake-workflows/dna-seq-*." },
          { type:"single",
            stem:"想用 cyvcf2 抓特定區段的 variants，前置條件？",
            stem_en:"To use cyvcf2 to fetch variants in a region, prerequisite is:",
            A:"VCF 必須是 .vcf.gz 並有 .tbi index", A_en:"VCF must be .vcf.gz with .tbi index",
            B:"VCF 必須是純文字未壓縮", B_en:"VCF must be plain uncompressed text",
            C:"必須先轉成 BAM", C_en:"Convert to BAM first",
            D:"必須先 BLAST", D_en:"BLAST first",
            ans:"A",
            exp:"區段查詢需 bgzip 壓縮 + tabix 建立 .tbi 索引；用 vcf(\"chr17:7670000-7690000\") 即可。",
            exp_en:"Region queries need bgzip + tabix .tbi index; then vcf(\"chr17:7670000-7690000\")." }
        ]
      },
      "單細胞與空間轉錄組": {
        "Ch 13：AnnData 與 scanpy 入門": [
          { type:"single",
            stem:"UMAP 座標儲存在 AnnData 的哪個欄位？",
            stem_en:"Where are UMAP coordinates stored in AnnData?",
            A:"adata.X", A_en:"adata.X",
            B:"adata.obs[\"umap\"]", B_en:"adata.obs[\"umap\"]",
            C:"adata.obsm[\"X_umap\"]", C_en:"adata.obsm[\"X_umap\"]",
            D:"adata.uns[\"umap\"]", D_en:"adata.uns[\"umap\"]",
            ans:"C",
            exp:"obsm 用於 cell × d 的多維資料；scanpy 一律以 X_ 前綴存（X_pca、X_umap、X_tsne）。",
            exp_en:"obsm holds cell × d multi-dim data; scanpy uses X_ prefix (X_pca, X_umap, X_tsne)." },
          { type:"single",
            stem:"adata.obs 是什麼？",
            stem_en:"adata.obs is:",
            A:"表達矩陣", A_en:"The expression matrix",
            B:"cell 端 metadata DataFrame（每列一 cell）", B_en:"Per-cell metadata DataFrame (one row per cell)",
            C:"gene 端 metadata", C_en:"Per-gene metadata",
            D:"顏色字典", D_en:"A color dictionary",
            ans:"B",
            exp:"obs = observations = cells；var = variables = genes。記住這個對應就不會搞混。",
            exp_en:"obs = observations = cells; var = variables = genes. Remember this mapping." },
          { type:"single",
            stem:"想保留原始 counts、又要存 lognorm 資料，最佳放置位置？",
            stem_en:"To keep both raw counts and log-normalized data, best slot is:",
            A:"adata.layers[\"counts\"] 與 adata.layers[\"lognorm\"]", A_en:"adata.layers[\"counts\"] and adata.layers[\"lognorm\"]",
            B:"兩個都覆蓋到 .X", B_en:"Overwrite .X twice",
            C:"存兩個 .h5ad 檔", C_en:"Save two .h5ad files",
            D:".obs 裡開兩個欄", D_en:"Two columns in .obs",
            ans:"A",
            exp:"layers 是同形狀矩陣的 dict；保留多版本表達矩陣的標準做法。",
            exp_en:"layers is a dict of same-shape matrices — the standard way to keep multiple expression versions." },
          { type:"multi",
            stem:"關於 AnnData 結構，下列敘述何者正確？（多選）",
            stem_en:"Which statements about AnnData structure are correct? (Multiple)",
            A:".X 通常為 scipy.sparse 矩陣以省記憶體", A_en:".X is typically scipy.sparse for memory efficiency",
            B:".obsp 用於存 cell pair 的距離 / connectivity", B_en:".obsp stores cell-cell distance / connectivity matrices",
            C:".uns 是任意 dict，可放 palette、rank_genes_groups 結果", C_en:".uns is an arbitrary dict (palettes, rank_genes_groups results)",
            D:".X 必須是 dense numpy ndarray", D_en:".X must be a dense numpy ndarray",
            ans:["A","B","C"],
            exp:"D 錯：.X 既可 dense (numpy)，也可 sparse (csr/csc)，視資料密度而定。",
            exp_en:"D is wrong: .X can be dense (numpy) or sparse (csr/csc), depending on density." },
          { type:"single",
            stem:"scanpy API 慣例 sc.pp / sc.tl / sc.pl 分別代表？",
            stem_en:"scanpy convention sc.pp / sc.tl / sc.pl stand for:",
            A:"preprocessing / tools / plotting", A_en:"preprocessing / tools / plotting",
            B:"package / tool / plot", B_en:"package / tool / plot",
            C:"private / public / library", C_en:"private / public / library",
            D:"前處理 / 線性代數 / 圖層", D_en:"preprocess / linear algebra / layer",
            ans:"A",
            exp:"pp = pre-process（修改 X / obs / var）；tl = tool（分析，存 obsm / uns）；pl = plot（畫圖）。",
            exp_en:"pp = pre-process (modifies X / obs / var); tl = tool (analysis, writes obsm / uns); pl = plot." },
          { type:"single",
            stem:"AnnData 物件最推薦的儲存格式為？",
            stem_en:"Most recommended save format for AnnData:",
            A:".csv", A_en:".csv",
            B:".h5ad（HDF5-based，速度與壓縮兼顧）", B_en:".h5ad (HDF5-based, fast + compressed)",
            C:".xlsx", C_en:".xlsx",
            D:".pdf", D_en:".pdf",
            ans:"B",
            exp:"h5ad 是 AnnData 原生格式，支援 sparse + 多 layer + obsm/uns 完整保存。",
            exp_en:".h5ad is AnnData's native format, preserving sparse + layers + obsm/uns completely." },
          { type:"single",
            stem:"切片 adata[:100] 回傳的物件特性是？",
            stem_en:"What does slicing adata[:100] return?",
            A:"AnnData 的 view（共用記憶體；要獨立要 .copy()）", A_en:"An AnnData view (shared memory; call .copy() for independence)",
            B:"完全獨立的副本", B_en:"A fully independent copy",
            C:"純 numpy ndarray", C_en:"A bare numpy ndarray",
            D:"pandas DataFrame", D_en:"A pandas DataFrame",
            ans:"A",
            exp:"與 NumPy 相似，AnnData 切片是 view；要修改不影響原物件須 .copy()。",
            exp_en:"Like NumPy, AnnData slices are views; copy with .copy() to detach." },
          { type:"tf",
            stem:"是非題：sc.pp.calculate_qc_metrics 會自動把 n_genes_by_counts、total_counts、pct_counts_mt 等欄位加進 adata.obs。",
            stem_en:"True/False: sc.pp.calculate_qc_metrics adds n_genes_by_counts, total_counts, pct_counts_mt etc. into adata.obs.",
            ans:"T",
            exp:"使用 inplace=True 後可省去手動計算；qc_vars 參數決定哪些 gene 群（mt/ribo/hb）要算比例。",
            exp_en:"With inplace=True it auto-fills metrics; qc_vars chooses which gene groups (mt/ribo/hb) to compute ratios for." }
        ],
        "Ch 14：scRNA-seq 完整流程": [
          { type:"single",
            stem:"sc.pp.normalize_total(target_sum=1e4) 之後該做什麼？",
            stem_en:"After sc.pp.normalize_total(target_sum=1e4), the next step is:",
            A:"直接 PCA", A_en:"PCA directly",
            B:"直接 UMAP", B_en:"UMAP directly",
            C:"sc.pp.log1p() — log 轉換以穩定變異", C_en:"sc.pp.log1p() — log transform to stabilize variance",
            D:"不用做了", D_en:"Nothing else",
            ans:"C",
            exp:"normalize → log1p → HVG → scale → PCA 是 scanpy 的標準前處理鏈。",
            exp_en:"normalize → log1p → HVG → scale → PCA is the standard scanpy preprocessing chain." },
          { type:"single",
            stem:"整合多樣本去除 batch effect 最常用的工具是？",
            stem_en:"Most common tools to remove batch effect when integrating samples:",
            A:"BWA", A_en:"BWA",
            B:"Harmony / scVI / scanorama", B_en:"Harmony / scVI / scanorama",
            C:"BLAST", C_en:"BLAST",
            D:"FastQC", D_en:"FastQC",
            ans:"B",
            exp:"Harmony 最快、scVI 深度學習效果穩、scanorama 用於 panoramic 整合。",
            exp_en:"Harmony is fastest; scVI uses deep learning robustly; scanorama for panoramic integration." },
          { type:"single",
            stem:"想找 cluster 0 的 marker genes，最直接的呼叫？",
            stem_en:"To find marker genes for cluster 0, the direct call is:",
            A:"sc.tl.rank_genes_groups(adata, \"leiden\")", A_en:"sc.tl.rank_genes_groups(adata, \"leiden\")",
            B:"sc.tl.umap(adata)", B_en:"sc.tl.umap(adata)",
            C:"sc.pp.scale(adata)", C_en:"sc.pp.scale(adata)",
            D:"sc.tl.pca(adata)", D_en:"sc.tl.pca(adata)",
            ans:"A",
            exp:"rank_genes_groups 預設 wilcoxon test 比較每個 cluster vs 其他；可用 sc.get.rank_genes_groups_df 取結果。",
            exp_en:"rank_genes_groups (Wilcoxon by default) compares each cluster vs the rest; sc.get.rank_genes_groups_df extracts the table." },
          { type:"single",
            stem:"Leiden resolution 參數的作用？",
            stem_en:"What does the Leiden resolution parameter control?",
            A:"控制 cluster 數量；數字越大、cluster 越多越細", A_en:"Controls the number of clusters — higher means more, finer clusters",
            B:"控制執行速度", B_en:"Controls run time",
            C:"控制圖檔解析度", C_en:"Controls figure DPI",
            D:"控制 PCA 主成分數", D_en:"Controls number of PCs",
            ans:"A",
            exp:"resolution 越高、cluster 越多。實務上多試幾個值（0.3, 0.5, 0.8, 1.2）找最對應生物意義的。",
            exp_en:"Higher resolution = more clusters. Try several values (0.3, 0.5, 0.8, 1.2) and choose the biologically meaningful one." },
          { type:"multi",
            stem:"關於 scRNA-seq 的 HVG 選擇，下列敘述正確？（多選）",
            stem_en:"Which statements about HVG selection are correct? (Multiple)",
            A:"通常選 2000-3000 個高變異基因", A_en:"Typically select 2000-3000 highly variable genes",
            B:"flavor='seurat_v3' 需要 raw counts (layer)", B_en:"flavor='seurat_v3' needs raw counts (layer)",
            C:"HVG 用於後續 PCA / UMAP 的輸入", C_en:"HVGs feed into downstream PCA / UMAP",
            D:"必須選全部基因，越多越好", D_en:"Must select all genes — the more the better",
            ans:["A","B","C"],
            exp:"D 錯：保留全部基因會引入大量噪音、且運算成本爆炸。HVG 是降低噪音的關鍵步驟。",
            exp_en:"D is wrong: keeping all genes adds huge noise and compute cost. HVG selection cuts noise effectively." },
          { type:"single",
            stem:"scanpy 把 cluster 投回組織切片（spatial）的 plot 函式為？",
            stem_en:"scanpy function to overlay clusters on a tissue section:",
            A:"sc.pl.umap", A_en:"sc.pl.umap",
            B:"sc.pl.spatial", B_en:"sc.pl.spatial",
            C:"sc.pl.tsne", C_en:"sc.pl.tsne",
            D:"sc.pl.violin", D_en:"sc.pl.violin",
            ans:"B",
            exp:"sc.pl.spatial 會用 adata.uns[\"spatial\"] 中的 HE 影像背景 + adata.obsm[\"spatial\"] 座標繪製。",
            exp_en:"sc.pl.spatial uses the HE image in adata.uns[\"spatial\"] and the coords in adata.obsm[\"spatial\"]." },
          { type:"tf",
            stem:"是非題：QC 過濾、normalize、HVG、scaling 結束後，PCA 的輸入是「scaled HVG 矩陣」。",
            stem_en:"True/False: After QC, normalize, HVG, and scaling, PCA's input is the \"scaled HVG matrix\".",
            ans:"T",
            exp:"標準流程下 PCA 用 scaled (z-scored) HVG-only 矩陣以避免高表達基因主導變異方向。",
            exp_en:"Standard PCA uses the z-scored HVG-only matrix to prevent highly expressed genes from dominating variation." },
          { type:"single",
            stem:"自動細胞註解工具中，下列何者較常被 scanpy 生態系使用？",
            stem_en:"Which automatic cell-type annotator is commonly used in the scanpy ecosystem?",
            A:"CellTypist", A_en:"CellTypist",
            B:"BWA", B_en:"BWA",
            C:"Picard", C_en:"Picard",
            D:"FastQC", D_en:"FastQC",
            ans:"A",
            exp:"CellTypist 提供大量預訓練模型；其他常見有 SingleR (R)、scArches reference mapping。",
            exp_en:"CellTypist ships many pretrained models; alternatives include SingleR (R) and scArches reference mapping." }
        ],
        "Ch 15：空間轉錄組 (Squidpy)": [
          { type:"single",
            stem:"Visium spot (~55 μm) 跟單細胞最大的差別是？",
            stem_en:"Biggest difference between a Visium spot (~55 μm) and a single cell?",
            A:"沒差", A_en:"No difference",
            B:"一個 spot 含多個細胞，需 deconvolution 才能拿到細胞組成", B_en:"A spot contains multiple cells; deconvolution is needed for cell-type composition",
            C:"spot 比較貴", C_en:"Spots are more expensive",
            D:"spot 不能跑 UMAP", D_en:"Spots can't run UMAP",
            ans:"B",
            exp:"Visium spot 是混合細胞，需用 cell2location/RCTD/Tangram 等以 scRNA 參考圖譜做 deconvolution。",
            exp_en:"A Visium spot is a cell mixture; deconvolve with cell2location/RCTD/Tangram using a scRNA reference." },
          { type:"single",
            stem:"找在空間上有結構（不只是 cluster 間差）的基因，最該用？",
            stem_en:"To find genes with structural variation in space (beyond cluster differences):",
            A:"sc.tl.rank_genes_groups", A_en:"sc.tl.rank_genes_groups",
            B:"sc.tl.umap", B_en:"sc.tl.umap",
            C:"sq.gr.spatial_autocorr (Moran's I) 或 SpatialDE", C_en:"sq.gr.spatial_autocorr (Moran's I) or SpatialDE",
            D:"標準 PCA", D_en:"Standard PCA",
            ans:"C",
            exp:"Moran's I 衡量空間自相關；高分基因表示「空間上有結構」（如沿層分佈）。",
            exp_en:"Moran's I measures spatial autocorrelation; high scores indicate spatial structure (e.g., layered patterns)." },
          { type:"single",
            stem:"處理 Xenium 含影像 + cell polygon 的資料，最佳容器？",
            stem_en:"Best container for Xenium data with images + cell polygons:",
            A:"SpatialData（整合 table + image + shape）", A_en:"SpatialData (unifies table + image + shape)",
            B:"純 AnnData", B_en:"Plain AnnData",
            C:"pandas DataFrame", C_en:"pandas DataFrame",
            D:"CSV 檔", D_en:"CSV file",
            ans:"A",
            exp:"SpatialData 是 scverse 新一代資料模型，整合 cell × gene、影像與多解析度幾何資料。",
            exp_en:"SpatialData is scverse's next-gen model unifying cell × gene tables, images, and multi-resolution geometry." },
          { type:"multi",
            stem:"下列哪些是空間轉錄組常見技術平台？（多選）",
            stem_en:"Which are common spatial transcriptomics platforms? (Multiple)",
            A:"10X Visium / Visium HD", A_en:"10X Visium / Visium HD",
            B:"10X Xenium", B_en:"10X Xenium",
            C:"MERFISH", C_en:"MERFISH",
            D:"Sanger 序列分析", D_en:"Sanger sequencing",
            ans:["A","B","C"],
            exp:"D 是上世紀 80 年代 DNA 定序技術，與空間轉錄組無關。",
            exp_en:"D is 1980s DNA sequencing — unrelated to spatial transcriptomics." },
          { type:"single",
            stem:"想分析「哪些 cluster 在空間上常常彼此相鄰」，squidpy 提供？",
            stem_en:"To analyze which clusters are often spatially adjacent, squidpy offers:",
            A:"sq.gr.nhood_enrichment / sq.gr.co_occurrence", A_en:"sq.gr.nhood_enrichment / sq.gr.co_occurrence",
            B:"sq.gr.umap", B_en:"sq.gr.umap",
            C:"sq.gr.fastqc", C_en:"sq.gr.fastqc",
            D:"sq.gr.blast", D_en:"sq.gr.blast",
            ans:"A",
            exp:"先 spatial_neighbors 建鄰居圖，再 nhood_enrichment / co_occurrence 量化空間共現。",
            exp_en:"Build a spatial_neighbors graph, then nhood_enrichment / co_occurrence to quantify co-presence in space." },
          { type:"single",
            stem:"Visium 的 cell type deconvolution 工具是？",
            stem_en:"Cell-type deconvolution tools for Visium:",
            A:"cell2location / RCTD / Tangram / Stereoscope", A_en:"cell2location / RCTD / Tangram / Stereoscope",
            B:"BWA", B_en:"BWA",
            C:"BLAST", C_en:"BLAST",
            D:"DESeq2", D_en:"DESeq2",
            ans:"A",
            exp:"這些工具用 scRNA-seq 參考來推估每 spot 的細胞組成。",
            exp_en:"These tools estimate per-spot cell composition using a scRNA-seq reference." },
          { type:"tf",
            stem:"是非題：scanpy 舊的 spatial 教學已被 deprecated；2024+ 推薦改用 squidpy + spatialdata 生態系。",
            stem_en:"True/False: scanpy's old spatial tutorial is deprecated; from 2024+ the recommended path is squidpy + spatialdata.",
            ans:"T",
            exp:"scverse 的官方推薦：教學整合到 squidpy；資料模型轉為 SpatialData。",
            exp_en:"scverse's official guidance: tutorials moved to squidpy; data model is now SpatialData." },
          { type:"single",
            stem:"Visium HD（2024 新一代）相比傳統 Visium 最大的進展是？",
            stem_en:"Biggest advance of Visium HD (2024+) vs classic Visium:",
            A:"解析度由 ~55 μm spot 提升至 2 μm bin（接近單細胞）", A_en:"Resolution improves from ~55 μm spot to 2 μm bin (near single-cell)",
            B:"沒有差別", B_en:"No difference",
            C:"變得只能測蛋白", C_en:"Now only measures proteins",
            D:"取消了 HE 影像", D_en:"Removes HE imaging",
            ans:"A",
            exp:"Visium HD 大幅提升空間解析度，已接近單細胞層級，能解析細胞層次的組織結構。",
            exp_en:"Visium HD greatly improves spatial resolution, approaching single-cell level for tissue structure analysis." }
        ]
      },
      "進階 AI 與多體學": {
        "Ch 16：多體學整合": [
          { type:"single",
            stem:"CITE-seq 同時測量什麼？",
            stem_en:"CITE-seq simultaneously measures:",
            A:"RNA + 染色質開放", A_en:"RNA + chromatin accessibility",
            B:"RNA + 表面蛋白（抗體 barcode）", B_en:"RNA + surface proteins (antibody-derived tags)",
            C:"RNA + DNA 突變", C_en:"RNA + DNA mutations",
            D:"RNA + 代謝物", D_en:"RNA + metabolites",
            ans:"B",
            exp:"CITE-seq = Cellular Indexing of Transcriptomes and Epitopes by Sequencing；用抗體 barcode 量化表面蛋白。",
            exp_en:"CITE-seq quantifies surface proteins via antibody-derived barcodes alongside RNA." },
          { type:"single",
            stem:"水平整合（同 omics、跨樣本去除 batch）最常用的工具是？",
            stem_en:"Most common tools for horizontal integration (same omics, cross-sample batch removal):",
            A:"totalVI", A_en:"totalVI",
            B:"MultiVI", B_en:"MultiVI",
            C:"Harmony / scVI / scanorama", C_en:"Harmony / scVI / scanorama",
            D:"BLAST", D_en:"BLAST",
            ans:"C",
            exp:"totalVI 為 RNA+protein 垂直整合；MultiVI 為 RNA+ATAC；水平整合用 Harmony/scVI/scanorama。",
            exp_en:"totalVI is for RNA+protein, MultiVI is for RNA+ATAC; horizontal use Harmony/scVI/scanorama." },
          { type:"single",
            stem:"MuData 與 AnnData 的關係？",
            stem_en:"Relationship between MuData and AnnData:",
            A:"MuData 是「裝多個 AnnData 的盒子」，每 modality 一個 AnnData", A_en:"MuData is a container of multiple AnnDatas, one per modality",
            B:"MuData 取代了 AnnData", B_en:"MuData replaces AnnData",
            C:"兩個沒關係", C_en:"Unrelated",
            D:"MuData 是 AnnData 的子類", D_en:"MuData is a subclass of AnnData",
            ans:"A",
            exp:"MuData = {modality_name: AnnData}；共享 .obs（cell metadata）、整合後 embedding 存於 .obsm。",
            exp_en:"MuData = {modality_name: AnnData}, with shared .obs and integrated embeddings in .obsm." },
          { type:"multi",
            stem:"下列哪些屬於垂直整合 (vertical integration) 場景？（多選）",
            stem_en:"Which are vertical integration scenarios? (Multiple)",
            A:"同一 cell 的 RNA + ATAC（Multiome）", A_en:"Same-cell RNA + ATAC (Multiome)",
            B:"同一 cell 的 RNA + 表面蛋白（CITE-seq）", B_en:"Same-cell RNA + surface protein (CITE-seq)",
            C:"不同樣本、相同 omics 移除 batch", C_en:"Different samples, same omics, batch removal",
            D:"Perturb-seq（RNA + CRISPR 擾動）", D_en:"Perturb-seq (RNA + CRISPR perturbation)",
            ans:["A","B","D"],
            exp:"C 屬於水平整合（Harmony/scVI 適用）；其他都是同 cell 多 omics 的垂直整合。",
            exp_en:"C is horizontal (Harmony/scVI); the others are same-cell multi-omics (vertical)." },
          { type:"single",
            stem:"想要可解釋的因子（哪個基因 + 哪個 peak 最重要），最適合的整合方法？",
            stem_en:"For interpretable factors (which gene + which peak), the best method:",
            A:"MOFA+", A_en:"MOFA+",
            B:"Harmony", B_en:"Harmony",
            C:"BWA", C_en:"BWA",
            D:"BLAST", D_en:"BLAST",
            ans:"A",
            exp:"MOFA+ 提供因子分解，每個 factor 都能反推哪個 feature 貢獻最大；scVI 系列偏黑盒。",
            exp_en:"MOFA+ provides factor decomposition with feature attribution; scVI-family models are more black-box." },
          { type:"single",
            stem:"處理 RNA + ATAC 同 cell 整合，最常用的深度學習方法為？",
            stem_en:"For same-cell RNA + ATAC integration, the common DL method is:",
            A:"MultiVI（scvi-tools 內）", A_en:"MultiVI (in scvi-tools)",
            B:"BWA", B_en:"BWA",
            C:"FastQC", C_en:"FastQC",
            D:"DESeq2", D_en:"DESeq2",
            ans:"A",
            exp:"MultiVI 是 scvi-tools 的 RNA+ATAC 整合 VAE，使用方式與 scVI 一致。",
            exp_en:"MultiVI is scvi-tools' RNA+ATAC VAE; usage mirrors scVI." },
          { type:"tf",
            stem:"是非題：「Omics」一詞泛指對某分子層次（如 transcriptomics、proteomics、epigenomics）做全方位測量。",
            stem_en:"True/False: \"Omics\" broadly refers to comprehensive measurement of a molecular layer (transcriptomics, proteomics, epigenomics).",
            ans:"T",
            exp:"-omics 後綴表示「全方位/全域研究」；多體學整合即跨層級的全域測量。",
            exp_en:"The -omics suffix means \"comprehensive\"; multi-omics integration spans multiple molecular layers." },
          { type:"single",
            stem:"處理 Perturb-seq（CRISPR + RNA）資料的常見工具是？",
            stem_en:"Common tools for Perturb-seq (CRISPR + RNA) data:",
            A:"Mixscape / scperturb", A_en:"Mixscape / scperturb",
            B:"BLAST", B_en:"BLAST",
            C:"BWA", C_en:"BWA",
            D:"FastQC", D_en:"FastQC",
            ans:"A",
            exp:"Mixscape (Seurat/scanpy) 與 scperturb 是處理 perturb-seq 的標準工具。",
            exp_en:"Mixscape (Seurat/scanpy) and scperturb are standard tools for perturb-seq." }
        ],
        "Ch 17：單細胞 LLMs (scLLMs)": [
          { type:"single",
            stem:"scLLM 把 cell 對應到 NLP 中的什麼？",
            stem_en:"In scLLMs, a cell maps to which NLP concept?",
            A:"一個字", A_en:"A word",
            B:"一個段落", B_en:"A paragraph",
            C:"一個句子；基因是字 (token)", C_en:"A sentence; genes are tokens",
            D:"整個語料庫", D_en:"The whole corpus",
            ans:"C",
            exp:"核心類比：cell = sentence、gene = token、表達量 = token strength/rank。",
            exp_en:"Core analogy: cell = sentence, gene = token, expression = token strength/rank." },
          { type:"single",
            stem:"2024-2025 基準測試顯示 scLLMs 在哪個任務目前較弱？",
            stem_en:"2024-2025 benchmarks suggest scLLMs are currently weakest at:",
            A:"擾動預測", A_en:"Perturbation prediction",
            B:"標準 zero-shot batch 整合（常輸給 scVI / Harmony）", B_en:"Standard zero-shot batch integration (often loses to scVI / Harmony)",
            C:"跨物種對應", C_en:"Cross-species mapping",
            D:"細胞註解", D_en:"Cell annotation",
            ans:"B",
            exp:"多份 2024-2025 基準（Kedzierska / Boiarsky）顯示 scLLMs 在 zero-shot 整合常不及傳統方法。",
            exp_en:"Multiple 2024-2025 benchmarks (Kedzierska / Boiarsky) show scLLMs often underperform classical methods on zero-shot integration." },
          { type:"single",
            stem:"Geneformer 的核心輸入表示法是？",
            stem_en:"Geneformer's core input representation is:",
            A:"基因表達量的 rank 順序（rank value encoding）", A_en:"Gene expression rank order (rank value encoding)",
            B:"連續表達量的浮點向量", B_en:"Continuous expression float vector",
            C:"染色質開放度", C_en:"Chromatin accessibility",
            D:"cell-cell distance matrix", D_en:"cell-cell distance matrix",
            ans:"A",
            exp:"Geneformer 把每 cell 表示為「基因表達 rank 序列」，丟進 transformer 學 embedding。",
            exp_en:"Geneformer encodes each cell as the rank order of expressed genes, fed into a transformer." },
          { type:"multi",
            stem:"下列哪些是現今主流的單細胞大型語言模型 (scLLM)？（多選）",
            stem_en:"Which are mainstream single-cell LLMs today? (Multiple)",
            A:"scGPT", A_en:"scGPT",
            B:"Geneformer", B_en:"Geneformer",
            C:"scFoundation", C_en:"scFoundation",
            D:"BWA-MEM2", D_en:"BWA-MEM2",
            ans:["A","B","C"],
            exp:"D 是短 read 比對器，與 scLLM 無關。",
            exp_en:"D is a short-read aligner — unrelated to scLLMs." },
          { type:"single",
            stem:"scGPT 訓練資料量級為？",
            stem_en:"scGPT was trained on roughly:",
            A:"幾百個 cells", A_en:"A few hundred cells",
            B:"~3.3 千萬 (33M) cells（multi-omics）", B_en:"~33 million cells (multi-omics)",
            C:"100 cells", C_en:"100 cells",
            D:"沒有訓練資料", D_en:"No training data",
            ans:"B",
            exp:"scGPT (Cui et al., Nature Methods 2024) 用 33M cells 預訓練；屬於 generative transformer。",
            exp_en:"scGPT (Cui et al., Nature Methods 2024) was pretrained on 33M cells with a generative transformer." },
          { type:"single",
            stem:"什麼情境下使用 scLLM 最有優勢？",
            stem_en:"When does using a scLLM offer the strongest advantage?",
            A:"樣本量很少 (<1000 cells) 或要做擾動預測", A_en:"Very small datasets (<1000 cells) or perturbation prediction",
            B:"標準 scRNA-seq 整合且已有好結果", B_en:"Standard scRNA-seq integration that already works well",
            C:"嚴格 reproducibility", C_en:"Strict reproducibility",
            D:"完全沒有 GPU", D_en:"Without any GPU",
            ans:"A",
            exp:"scLLM 在小樣本與 perturb-seq 預測上能利用大型預訓練語料；其他情境較難勝過 scVI / Harmony。",
            exp_en:"scLLMs leverage large pretraining corpora best for small datasets and perturb-seq prediction; otherwise hard to beat scVI / Harmony." },
          { type:"tf",
            stem:"是非題：scGPT 與 Geneformer 的 zero-shot embedding 永遠優於 scVI / Harmony 等傳統方法。",
            stem_en:"True/False: scGPT and Geneformer's zero-shot embeddings always outperform classical methods like scVI / Harmony.",
            ans:"F",
            exp:"恰恰相反——多份 2024-2025 基準顯示 zero-shot 仍常不及傳統方法；應視 scLLM 為工具而非神。",
            exp_en:"Quite the opposite — 2024-2025 benchmarks show zero-shot often loses to classical methods. Treat scLLMs as tools, not oracles." },
          { type:"single",
            stem:"UCE (Universal Cell Embeddings) 的最大特色是？",
            stem_en:"UCE (Universal Cell Embeddings) is best known for:",
            A:"跨物種統一 embedding（8 種以上物種共訓練）", A_en:"Cross-species unified embedding (trained on 8+ species)",
            B:"只能用人類資料", B_en:"Human-only",
            C:"完全不能 fine-tune", C_en:"Cannot be fine-tuned",
            D:"必須 CPU 跑", D_en:"CPU-only",
            ans:"A",
            exp:"UCE (Rosen et al., 2023) 用 36M cells、8+ 物種訓練，提供跨物種統一 embedding 空間。",
            exp_en:"UCE (Rosen et al., 2023) trained on 36M cells across 8+ species, providing a unified cross-species embedding space." }
        ],
        "Ch 18：AI 在生物資訊應用": [
          { type:"single",
            stem:"想知道一個人類蛋白的 3D 結構，本機沒 GPU，最快的方法？",
            stem_en:"Want a human protein 3D structure but have no local GPU — fastest path?",
            A:"自己跑本機 AlphaFold 2", A_en:"Run AlphaFold 2 locally",
            B:"自己做 X-ray 結晶", B_en:"Solve X-ray crystallography",
            C:"從 AlphaFold DB 用 UniProt ID 直接下載 PDB", C_en:"Download from AlphaFold DB by UniProt ID",
            D:"找朋友算", D_en:"Ask a friend",
            ans:"C",
            exp:"AlphaFold DB（alphafold.ebi.ac.uk）已預測 2 億+ 結構，UniProt ID 直接抓 PDB。",
            exp_en:"AlphaFold DB (alphafold.ebi.ac.uk) hosts 200M+ predictions; fetch PDB by UniProt ID instantly." },
          { type:"single",
            stem:"PyTorch 中 requires_grad=True 的作用？",
            stem_en:"What does requires_grad=True do in PyTorch?",
            A:"啟用自動微分，記錄計算圖以便 backward()", A_en:"Enables autograd; tracks the computation graph for backward()",
            B:"把 tensor 轉成 numpy", B_en:"Converts tensor to numpy",
            C:"自動移到 GPU", C_en:"Auto-moves to GPU",
            D:"加密張量", D_en:"Encrypts the tensor",
            ans:"A",
            exp:"requires_grad=True 讓 PyTorch 追蹤對該 tensor 的所有操作，呼叫 .backward() 才能算梯度。",
            exp_en:"requires_grad=True makes PyTorch track all ops on the tensor so .backward() can compute gradients." },
          { type:"single",
            stem:"ESM-2 預訓練模型最大的用途是？",
            stem_en:"Main use of pretrained ESM-2:",
            A:"取代基因組序列比對", A_en:"Replace genome alignment",
            B:"給每條蛋白序列產生 embedding；下游可做分類 / 突變影響預測", B_en:"Generate per-protein embeddings; downstream classification / variant effect prediction",
            C:"取代細胞註解", C_en:"Replace cell annotation",
            D:"預測 SNP", D_en:"Predict SNPs",
            ans:"B",
            exp:"ESM-2 是蛋白質語言模型，輸出每位置 embedding，可用於蛋白功能、突變影響、distant homology。",
            exp_en:"ESM-2 is a protein LM giving per-position embeddings — used for function, variant effect, and distant homology." },
          { type:"multi",
            stem:"下列哪些是 AI × 生資的代表模型 / 工具？（多選）",
            stem_en:"Which are landmark AI × bio models / tools? (Multiple)",
            A:"AlphaFold 2 / 3（蛋白結構）", A_en:"AlphaFold 2 / 3 (protein structure)",
            B:"ESM-2（蛋白語言模型）", B_en:"ESM-2 (protein LM)",
            C:"Enformer（DNA → 表達 / 調控預測）", C_en:"Enformer (DNA → expression / regulatory prediction)",
            D:"Microsoft Word", D_en:"Microsoft Word",
            ans:["A","B","C"],
            exp:"D 是文書處理軟體；前三項分別代表結構、序列、基因組三大 AI 應用領域。",
            exp_en:"D is word processing; the others span structure, sequence, and genomic AI." },
          { type:"single",
            stem:"PyTorch 中 NumPy ↔ Tensor 的標準轉換方式？",
            stem_en:"Standard NumPy ↔ Tensor conversion in PyTorch:",
            A:"torch.from_numpy(arr) 與 t.cpu().numpy()", A_en:"torch.from_numpy(arr) and t.cpu().numpy()",
            B:"必須先轉成 list", B_en:"Must convert to list first",
            C:"不可互轉", C_en:"Not interconvertible",
            D:"用 pandas", D_en:"Use pandas",
            ans:"A",
            exp:"GPU 上的 tensor 必須先 .cpu() 才能 .numpy()；CPU 上的 tensor 與 numpy 共享記憶體。",
            exp_en:"GPU tensors must .cpu() before .numpy(); CPU tensors share memory with numpy." },
          { type:"single",
            stem:"要在筆電上預測蛋白質結構，速度遠快於 AlphaFold 2 但需要 GPU 的選擇？",
            stem_en:"On a laptop with GPU, fastest protein structure predictor (much faster than AlphaFold 2):",
            A:"ESMFold（無需 MSA、單序列預測）", A_en:"ESMFold (no MSA needed, single-sequence prediction)",
            B:"BLAST", B_en:"BLAST",
            C:"BWA", C_en:"BWA",
            D:"FastQC", D_en:"FastQC",
            ans:"A",
            exp:"ESMFold 用 ESM-2 + 結構解碼器，無需 MSA，速度比 AF2 快約 60×，準確度略低但夠多數應用。",
            exp_en:"ESMFold combines ESM-2 + structure decoder, requires no MSA, ~60× faster than AF2 with slightly lower accuracy but adequate for most uses." },
          { type:"tf",
            stem:"是非題：訓練深度學習模型時，必須先 opt.zero_grad() 再 loss.backward()，否則梯度會累積。",
            stem_en:"True/False: When training, you must opt.zero_grad() before loss.backward(); otherwise gradients accumulate.",
            ans:"T",
            exp:"PyTorch 的梯度預設累積；標準訓練步驟：zero_grad() → forward → loss → backward() → optimizer.step()。",
            exp_en:"PyTorch accumulates gradients by default; standard step: zero_grad() → forward → loss → backward() → optimizer.step()." },
          { type:"single",
            stem:"實務上 Boltz-1 / DiffDock 等屬於哪個 AI × 生資領域？",
            stem_en:"Boltz-1 / DiffDock belong to which AI × biology area?",
            A:"蛋白-小分子對接 / 藥物設計", A_en:"Protein-ligand docking / drug design",
            B:"短 read 比對", B_en:"Short-read alignment",
            C:"FASTQ 壓縮", C_en:"FASTQ compression",
            D:"Excel 分析", D_en:"Excel analysis",
            ans:"A",
            exp:"DiffDock / Boltz-1 / AlphaFold 3 都涉及蛋白-小分子或蛋白-蛋白對接，是現代 AI 藥物設計的核心。",
            exp_en:"DiffDock / Boltz-1 / AlphaFold 3 handle protein-ligand or protein-protein docking — core to modern AI drug design." }
        ]
      }
    }
  }
};
